	
	CREATE VIEW LOG_CONTATO_LOJA_EXPIRADO AS
	SELECT CODIGO_PARCEIRO,CODIGO_LOJA_PARAN,CODIGO_LOJA,DESCRICAO_LOJA,ATIVACAO_LOJA,STATUS_LOJA,FAZER_CONTATO,
	DATA_EXPIRACAO FROM TB_LOJA WHERE ATIVACAO_LOJA='S' AND   FAZER_CONTATO='N' AND DATA_EXPIRACAO <= GETDATE()

	
	SELECT * FROM LOG_CONTATO_LOJA_EXPIRADO