
USE BRA_SOLUCOES_PDV

CREATE VIEW  LOG_LOJA_FALTANTE AS 
--LOJA NÃO CADASTRADA
SELECT DISTINCT MV.CODIGO_PARCEIRO, MV.CODIGO_LOJA, l.CODIGO_LOJA_NOVOFRONT
	FROM MONITORIA_VENDA MV
	LEFT JOIN LOJA AS l ON MV.CODIGO_PARCEIRO = l.CODIGO_PARCEIRO and MV.CODIGO_LOJA = l.CODIGO_LOJA_NOVOFRONT
	WHERE  l.CODIGO_LOJA_NOVOFRONT IS NULL

	UNION
--PARCEIRO NÃO CADASTRADO
SELECT DISTINCT MV.CODIGO_PARCEIRO, MV.CODIGO_LOJA, NULL as CODIGO_LOJA_NOVOFRONT
	FROM MONITORIA_VENDA MV
	LEFT JOIN PARCEIRO as P on MV.CODIGO_PARCEIRO = P.CODIGO_PARCEIRO 
	WHERE  MV.CODIGO_PARCEIRO IS NULL

SELECT * FROM LOG_LOJA_FALTANTE


