
CREATE PROCEDURE MONITORIA_3_MESES 

@DATA_MONITORIA DATE

AS BEGIN

IF OBJECT_ID('BRA_SOLUCOES_PDV..MONITORIA_VENDA') IS NOT NULL
	BEGIN
		DELETE FROM MONITORIA_VENDA
	END;


INSERT INTO MONITORIA_VENDA
SELECT 
	VDN.CODIGO_PARCEIRO, 
	P.DESCRICAO_PARCEIRO,
	VDN.CODIGO_LOJA,
	L.DESCRICAO_LOJA,
	VDN.DATA_ACAO,
	CASE DATEPART(DW,VDN.DATA_ACAO)
		WHEN 1 THEN '1-DOMINGO' 
		WHEN 2 THEN '2-SEGUNDA-FEIRA' 
		WHEN 3 THEN '3-TERÇA-FEIRA' 
		WHEN 4 THEN '4-QUARTA-FEIRA' 
		WHEN 5 THEN '5-QUINTA-FEIRA' 
		WHEN 6 THEN '6-SEXTA-FEIRA' 
		WHEN 7 THEN '7-SABADO'
	END AS DIA_SEMANA_VENDA,
	ISNULL(SUM (case when DESCRITIVO = 'ENVIADO CONSULTA PREVIA'	OR DESCRITIVO = 'CONSULTA PRÉVIA'   THEN QUANTIDADE END),0) AS QTD_CONSULTA_PREVIA,
	ISNULL(SUM (case when DESCRITIVO = 'APROVADO CONSULTA PREVIA'	OR DESCRITIVO = 'PRÉVIA APROVADA'	THEN QUANTIDADE END),0) AS QTD_PREVIA_APROVADA,
	ISNULL(SUM (case when DESCRITIVO = 'EM DIGITAÇÃO'				OR DESCRITIVO = 'PROPOSTA'			THEN QUANTIDADE END),0) AS QTD_PROPOSTA,
	ISNULL(SUM (case when DESCRITIVO = 'CONTAS APROVADAS'			OR DESCRITIVO = 'ADESÃO'			THEN QUANTIDADE END),0) AS QTD_ADESAO
FROM VENDA_DIARIA_NOVOFRONT VDN
LEFT JOIN LOJA L ON L.CODIGO_PARCEIRO = VDN.CODIGO_PARCEIRO AND L.CODIGO_LOJA_NOVOFRONT = VDN.CODIGO_LOJA
LEFT JOIN PARCEIRO P ON P.CODIGO_PARCEIRO = VDN.CODIGO_PARCEIRO
WHERE VDN.DATA_ACAO  BETWEEN	(SELECT DATEADD(MONTH,-3, @DATA_MONITORIA))	AND	(SELECT @DATA_MONITORIA)
	  AND L.SISTEMA_ORIGINACAO LIKE '%NOVO FRONT%'
	  AND L.ATIVACAO_LOJA = 'S'	
	  AND L.STATUS_LOJA	  = 'ABERTA'
GROUP BY 
	VDN.CODIGO_PARCEIRO,
	P.DESCRICAO_PARCEIRO,
	VDN.CODIGO_LOJA,
	L.DESCRICAO_LOJA,
	VDN.DATA_ACAO
END

-----EXTRAÇÃO MONITORIA
DECLARE @DATA_ANALISE AS DATE
SET @DATA_ANALISE =GETDATE()-1 -- <<-- INFORME A DATA DE APURAÇÃO DA MONITORIA

EXEC MONITORIA_3_MESES  @DATA_ANALISE  -- <<-- INFORME A DATA DE APURAÇÃO DA MONITORIA

SELECT * FROM MONITORIA_VENDA

