
USE BRA_SOLUCOES_PDV

CREATE PROCEDURE MONITORIA_VENDAS_ABAIXO_MEDIA AS
BEGIN
	--CALCULANDO MEDIA TRIMESTRAL
	IF OBJECT_ID('TEMPDB..#MEDIA_TRIMESTRAL_VENDA') IS NOT NULL
		BEGIN
			DROP TABLE #MEDIA_TRIMESTRAL_VENDA
		END;

	CREATE TABLE #MEDIA_TRIMESTRAL_VENDA
		(
			CODIGO_PARCEIRO				VARCHAR(10),          
			DESCRICAO_PARCEIRO			VARCHAR(30),
			CODIGO_LOJA					VARCHAR(10),
			DIA_SEMANA_VENDA			VARCHAR(20),
			MEDIA_TRES_MESES_SEGUNDA	FLOAT(3), 
			MEDIA_TRES_MESES_TERCA		FLOAT(3), 
			MEDIA_TRES_MESES_QUARTA		FLOAT(3), 
			MEDIA_TRES_MESES_QUINTA		FLOAT(3), 
			MEDIA_TRES_MESES_SEXTA		FLOAT(3), 
			MEDIA_TRES_MESES_SABADO		FLOAT(3), 
			MEDIA_TRES_MESES_DOMINGO	FLOAT(3), 
		)

	INSERT INTO #MEDIA_TRIMESTRAL_VENDA
	SELECT
			MV.CODIGO_PARCEIRO,
			MV.DESCRICAO_PARCEIRO,
			MV.CODIGO_LOJA,
			MV.DIA_SEMANA_VENDA,
			ROUND (SUM	(CASE WHEN DIA_SEMANA_VENDA = '2-SEGUNDA-FEIRA' THEN QTDE_CONSULTA_PREVIA END)
				/COUNT	(CASE WHEN DIA_SEMANA_VENDA = '2-SEGUNDA-FEIRA' THEN QTDE_CONSULTA_PREVIA END),0) AS MEDIA_TRES_MESES_SEGUNDA,

			ROUND (SUM	(CASE WHEN DIA_SEMANA_VENDA = '3-TERÇA-FEIRA' THEN QTDE_CONSULTA_PREVIA END)
				/COUNT	(CASE WHEN DIA_SEMANA_VENDA = '3-TERÇA-FEIRA' THEN QTDE_CONSULTA_PREVIA END),0) AS MEDIA_TRES_MESES_TERCA,

			ROUND (SUM(CASE	WHEN DIA_SEMANA_VENDA = '4-QUARTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END)
				/COUNT(CASE WHEN DIA_SEMANA_VENDA = '4-QUARTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END),0) AS MEDIA_TRES_MESES_QUARTA,

			ROUND (SUM(CASE WHEN DIA_SEMANA_VENDA = '5-QUINTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END)
				/COUNT(CASE WHEN DIA_SEMANA_VENDA = '5-QUINTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END),0) AS MEDIA_TRES_MESES_QUINTA,

			ROUND (SUM(CASE WHEN DIA_SEMANA_VENDA = '6-SEXTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END)
				/COUNT(CASE WHEN DIA_SEMANA_VENDA = '6-SEXTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END),0) AS MEDIA_TRES_MESES_SEXTA,

			ROUND (SUM(CASE WHEN DIA_SEMANA_VENDA = '7-SABADO' THEN QTDE_CONSULTA_PREVIA END)
				/COUNT(CASE WHEN DIA_SEMANA_VENDA = '7-SABADO' THEN QTDE_CONSULTA_PREVIA END),0) AS MEDIA_TRES_MESES_SABADO,

			ROUND (SUM(CASE WHEN DIA_SEMANA_VENDA = '1-DOMINGO' THEN QTDE_CONSULTA_PREVIA END)
				/COUNT(CASE WHEN DIA_SEMANA_VENDA = '1-DOMINGO' THEN QTDE_CONSULTA_PREVIA END),0) AS MEDIA_TRES_MESES_DOMINGO

	FROM MONITORIA_VENDA MV
	LEFT JOIN LOJA AS L	ON MV.CODIGO_PARCEIRO = L.CODIGO_PARCEIRO AND MV.CODIGO_LOJA = L.CODIGO_LOJA_NOVOFRONT								
	WHERE L.FAZER_CONTATO = 'S'
	GROUP BY MV.CODIGO_PARCEIRO,MV.DESCRICAO_PARCEIRO,MV.CODIGO_LOJA,MV.DIA_SEMANA_VENDA
	ORDER BY CODIGO_LOJA

	--SELECT * FROM #MEDIA_TRIMESTRAL_VENDA

	--CALCULANDO MÉDIA SEMANAL
	IF OBJECT_ID('TEMPDB..#MEDIA_SEMANAL_VENDA') IS NOT NULL
		BEGIN
			DROP TABLE #MEDIA_SEMANAL_VENDA
		END;

	CREATE TABLE #MEDIA_SEMANAL_VENDA
		(
			CODIGO_PARCEIRO		VARCHAR(10),          
			DESCRICAO_PARCEIRO	VARCHAR(30),
			CODIGO_LOJA			VARCHAR(10),
			MEDIA_SEMANAL		FLOAT(3)
		)

	INSERT INTO #MEDIA_SEMANAL_VENDA
	SELECT
			MV.CODIGO_PARCEIRO,
			MV.DESCRICAO_PARCEIRO,
			MV.CODIGO_LOJA,
			SUM( QTDE_CONSULTA_PREVIA) /COUNT(QTDE_CONSULTA_PREVIA) AS MEDIA_SEMANAL		
	FROM MONITORIA_VENDA MV
	LEFT JOIN LOJA L ON MV.CODIGO_PARCEIRO = L.CODIGO_PARCEIRO AND MV.CODIGO_LOJA = L.CODIGO_LOJA_NOVOFRONT
	WHERE	DATA_VENDA > (SELECT DATEADD(WEEK, -1,MAX(DATA_VENDA)) FROM MONITORIA_VENDA)
	AND		L.FAZER_CONTATO = 'S'
	GROUP BY MV.CODIGO_PARCEIRO,MV.DESCRICAO_PARCEIRO,MV.CODIGO_LOJA
	ORDER BY CODIGO_LOJA

	--SELECT * FROM #MEDIA_SEMANAL_VENDA

	--SELECIONANDO AS MÉDIAS DO DIA DA SEMANA DA ÚLTIMA IMPORTAÇÃO
	IF OBJECT_ID('TEMPDB..#VARIACAO_MEDIA') IS NOT NULL
		BEGIN
			DROP TABLE #VARIACAO_MEDIA
		END;

	CREATE TABLE #VARIACAO_MEDIA
		(
			CODIGO_PARCEIRO		VARCHAR(10),
			DESCRICAO_PARCEIRO	VARCHAR(30),
			CODIGO_LOJA			VARCHAR(10),
			DIA_SEMANA_VENDA	VARCHAR(20),
			MEDIA_TRIMESTRAL	FLOAT(3),
		)

	INSERT INTO #VARIACAO_MEDIA
	SELECT	MT.CODIGO_PARCEIRO,
			MT.DESCRICAO_PARCEIRO,
			MT.CODIGO_LOJA,
			MT.DIA_SEMANA_VENDA,
			CASE 
				WHEN MT.DIA_SEMANA_VENDA = '2-SEGUNDA-FEIRA'	THEN MT.MEDIA_TRES_MESES_SEGUNDA
				WHEN MT.DIA_SEMANA_VENDA = '3-TERÇA-FEIRA'		THEN MT.MEDIA_TRES_MESES_TERCA
				WHEN MT.DIA_SEMANA_VENDA = '4-QUARTA-FEIRA'		THEN MT.MEDIA_TRES_MESES_QUARTA
				WHEN MT.DIA_SEMANA_VENDA = '5-QUINTA-FEIRA'		THEN MT.MEDIA_TRES_MESES_QUINTA
				WHEN MT.DIA_SEMANA_VENDA = '6-SEXTA-FEIRA'		THEN MT.MEDIA_TRES_MESES_SEXTA
				WHEN MT.DIA_SEMANA_VENDA = '7-SABADO'			THEN MT.MEDIA_TRES_MESES_SABADO
				WHEN MT.DIA_SEMANA_VENDA = '1-DOMINGO'			THEN MT.MEDIA_TRES_MESES_DOMINGO
			END AS MEDIA_TRIMESTRAL
	FROM  #MEDIA_TRIMESTRAL_VENDA	AS MT
	WHERE MT.DIA_SEMANA_VENDA = (SELECT DISTINCT DIA_SEMANA_VENDA FROM MONITORIA_VENDA WHERE DATA_VENDA = (SELECT MAX(DATA_VENDA) FROM MONITORIA_VENDA))
	ORDER BY CODIGO_LOJA
	
	--SELECT * FROM #VARIACAO_MEDIA ORDER BY CODIGO_LOJA ASC

	--SELECIONANDO AS LOJAS QUE ESTÃO VENDENDO ABAIXO DA MEDIA/2
	IF OBJECT_ID('BRA_SOLUCOES_PDV..MONITORIA_ERROS') IS NOT NULL
		BEGIN
			DELETE FROM MONITORIA_ERROS
		END;

	INSERT INTO MONITORIA_ERROS
		SELECT	MV.CODIGO_PARCEIRO,
				MV.DESCRICAO_PARCEIRO,
				MV.CODIGO_LOJA,
				MV.DESCRICAO_LOJA,
				MV.DIA_SEMANA_VENDA,
				MV.DATA_VENDA,
				MV.QTDE_CONSULTA_PREVIA AS QTDE_VENDA_DIARIA,
				ISNULL(MS.MEDIA_SEMANAL,0),
				VM.MEDIA_TRIMESTRAL,
				L.ENDERECO_LOJA,
				L.BAIRRO_LOJA,
				L.CIDADE_LOJA,
				L.UF_LOJA,
				L.CEP_LOJA,
				L.TELEFONE_LOJA,
				L.CELULAR_LOJA,
				L.EMAIL_LOJA,
				L.ATIVACAO_LOJA	
		FROM MONITORIA_VENDA AS MV
		LEFT JOIN	LOJA					AS L  ON MV.CODIGO_PARCEIRO = L.CODIGO_PARCEIRO  AND MV.CODIGO_LOJA = L.CODIGO_LOJA_NOVOFRONT
		LEFT JOIN 	#VARIACAO_MEDIA			AS VM ON MV.CODIGO_PARCEIRO = VM.CODIGO_PARCEIRO AND MV.CODIGO_LOJA = VM.CODIGO_LOJA
		LEFT JOIN 	#MEDIA_SEMANAL_VENDA	AS MS ON MV.CODIGO_PARCEIRO = MS.CODIGO_PARCEIRO AND MV.CODIGO_LOJA = MS.CODIGO_LOJA
		WHERE	VM.MEDIA_TRIMESTRAL > 0
		AND		MV.QTDE_CONSULTA_PREVIA < = VM.MEDIA_TRIMESTRAL/2
		AND		L.FAZER_CONTATO = 'S' 
		AND		MV.DATA_VENDA = (SELECT MAX(DATA_VENDA) FROM MONITORIA_VENDA)
		ORDER BY VM.MEDIA_TRIMESTRAL, VM.CODIGO_LOJA
END

--SELECT * FROM MONITORIA_ERROS

EXEC MONITORIA_VENDAS_ABAIXO_MEDIA



