
USE BRA_SOLUCOES_PDV

SELECT	DESCRICAO_PARCEIRO,
		CODIGO_LOJA,
		DATA_VENDA,
		DIA_SEMANA_VENDA,
		QTDE_CONSULTA_PREVIA,
		QTDE_PREVIA_APROVADA,
		QTDE_PROPOSTA,
		QTDE_ADESAO
		FROM MONITORIA_VENDA
ORDER BY DESCRICAO_PARCEIRO,CODIGO_LOJA,DATA_VENDA

