
USE BRA_SOLUCOES_PDV

SELECT	MV.DATA_VENDA,
		MV.DIA_SEMANA_VENDA,
		MV.DESCRICAO_PARCEIRO,
		MV.CODIGO_LOJA,
		ME.DESCRICAO_LOJA,
		MV.QTDE_CONSULTA_PREVIA,
		MV.QTDE_PREVIA_APROVADA,
		MV.QTDE_PROPOSTA,
		MV.QTDE_ADESAO
FROM MONITORIA_ERROS AS ME
INNER JOIN MONITORIA_VENDA AS MV ON ME.CODIGO_PARCEIRO = MV.CODIGO_PARCEIRO AND ME.CODIGO_LOJA = MV.CODIGO_LOJA
ORDER BY MV.DATA_VENDA DESC


