
USE BRA_SOLUCOES_PDV

CREATE TABLE LOJA 
	(
	CODIGO_PARCEIRO			VARCHAR	(10) NOT NULL,
	CODIGO_LOJA_PARAN		VARCHAR	(10),
	CODIGO_LOJA_NOVOFRONT	VARCHAR	(10),
	REGIONAL				VARCHAR	(50),
	CODIGO_LOJA				VARCHAR	(10) NOT NULL,
	DESCRICAO_LOJA			VARCHAR	(50),
	ENDERECO_LOJA			VARCHAR	(255),
	BAIRRO_LOJA				VARCHAR	(100),
	CIDADE_LOJA				VARCHAR	(100),
	UF_LOJA					VARCHAR	(2),
	CEP_LOJA				VARCHAR	(10),
	TELEFONE_LOJA			VARCHAR	(20),
	CELULAR_LOJA			VARCHAR	(20),
	EMAIL_LOJA				VARCHAR	(50),
	ATIVACAO_LOJA			VARCHAR	(1),
	STATUS_LOJA				VARCHAR	(10),
	BIOMETRIA				VARCHAR	(1),
	FAZER_CONTATO			VARCHAR	(1),
	DATA_EXPIRACAO			DATE,
	SISTEMA_ORIGINACAO		VARCHAR	(50),
	SISTEMA_ATENDIMENTO		VARCHAR	(50),
	HORARIO_FUNCIONAMENTO	VARCHAR	(50),
	DATA_IMPORTACAO			DATE
	)

ALTER TABLE LOJA
ADD CONSTRAINT PK_COD_LOJA	PRIMARY KEY CLUSTERED (CODIGO_LOJA)

ALTER TABLE LOJA
ADD CONSTRAINT FK_LOJA_COD_PARCEIRO	FOREIGN KEY	(CODIGO_PARCEIRO) REFERENCES PARCEIRO;

SELECT * FROM LOJA


