USE BRA_SOLUCOES_PDV


CREATE TABLE VENDA_DIARIA_NOVOFRONT
	(

	CODIGO_PARCEIRO	VARCHAR(10) NOT NULL,
	CODIGO_LOJA		VARCHAR(10) NOT NULL,
	CODIGO_PROMOTOR	VARCHAR(20),
	ORG_LOGO		VARCHAR(10),
	MIGRACAO		VARCHAR	(1),
	DESCRITIVO		VARCHAR	(50),
	QUANTIDADE		INT,
	DATA_ACAO		DATE,
	DATA_IMPORTACAO_ARQUIVO DATE,
	ARQUIVO_IMPORTACAO VARCHAR(3)
	)

SELECT * FROM VENDA_DIARIA_NOVOFRONT