
USE BRA_SOLUCOES_PDV

CREATE TABLE MONITORIA_ERROS
		(
			CODIGO_PARCEIRO			VARCHAR(10) NOT NULL,
			DESCRICAO_PARCEIRO		VARCHAR(15),
			CODIGO_LOJA				VARCHAR(10) NOT NULL,		
			DESCRICAO_LOJA			VARCHAR(50),
			DIA_SEMANA_VENDA		VARCHAR(20),
			DATA_VENDA				DATE,
			QTD_VENDA_DIARIA		INT,
			MEDIA_SEMANAL			INT,
			MEDIA_DIARIA_TRIMESTRAL	INT,
			ENDERECO_LOJA			VARCHAR(100),
			BAIRRO_LOJA				VARCHAR(60),
			CIDADE_LOJA				VARCHAR(50),
			UF_LOJA					VARCHAR(2),
			CEP_LOJA				VARCHAR(9),
			TELEFONE_LOJA			VARCHAR(16),
			CELULAR_LOJA			VARCHAR(16),
			EMAIL_LOJA				VARCHAR(70),
			ATIVACAO_LOJA			VARCHAR(1)
		)

SELECT * FROM MONITORIA_ERROS

