
USE BRA_SOLUCOES_PDV

CREATE TABLE MONITORIA_VENDA
	(
		CODIGO_PARCEIRO		 VARCHAR(10) NOT NULL,
		DESCRICAO_PARCEIRO	 VARCHAR(30),
		CODIGO_LOJA			 VARCHAR(10) NOT NULL,
		DESCRICAO_LOJA		 VARCHAR(50),
		DATA_VENDA			 DATE, 
		DIA_SEMANA_VENDA	 VARCHAR(20),
		QTDE_CONSULTA_PREVIA INT,
		QTDE_PREVIA_APROVADA INT,
		QTDE_PROPOSTA		 INT,
		QTDE_ADESAO			 INT,
	)


SELECT * FROM MONITORIA_VENDA

