
USE BRA_SOLUCOES_PDV

CREATE TABLE PARCEIRO 
	(
		CODIGO_PARCEIRO		    VARCHAR(10) NOT NULL,
		DESCRICAO_PARCEIRO		VARCHAR	(30),
		ATEND_CENTRALIZADO		VARCHAR	(1),
		FONE_ATEND_CENTRALIZADO	VARCHAR	(20),
	)

ALTER TABLE PARCEIRO
ADD CONSTRAINT PK_COD_PARCEIRO	PRIMARY KEY (CODIGO_PARCEIRO)

SELECT * FROM PARCEIRO