USE BRADESCARD


IF OBJECT_ID('TEMPDB..#TEMP_DATA_VENDA') IS NOT NULL
		BEGIN
			DROP TABLE #TEMP_DATA_VENDA
		END

SELECT DISTINCT DATA_VENDA
INTO #TEMP_DATA_VENDA 
FROM MONITORIA_VENDA 
WHERE MONTH(DATA_VENDA) = 07	--<< INFORMAR O MES ATUAL OU MES DESEJADO
ORDER BY DATA_VENDA

DECLARE @COLUNAS VARCHAR(MAX)
SET @COLUNAS = ''

SELECT @COLUNAS = COALESCE(@COLUNAS + '[' + (CAST(DATA_VENDA AS NVARCHAR(255))) + '],','')
FROM (SELECT DATA_VENDA FROM  #TEMP_DATA_VENDA) AS DADOS_HORIZONTAIS
SET @COLUNAS = LEFT(@COLUNAS, LEN(@COLUNAS)-1)

PRINT @COLUNAS

DECLARE @SQL_STRING VARCHAR(MAX)
SET @SQL_STRING =
'SELECT * FROM
(
	SELECT DESCRICAO_PARCEIRO,
	DATA_VENDA,
	SUM(QTDE_ADESAO) AS QTDE_ADESAO
	FROM MONITORIA_VENDA
	WHERE DESCRICAO_PARCEIRO = ''LASA''
	OR DESCRICAO_PARCEIRO = ''COOP''
	OR DESCRICAO_PARCEIRO = ''MAKRO''
	GROUP BY 
	DESCRICAO_PARCEIRO,
	DATA_VENDA
) AS DADOS_HORIZONTAIS
		PIVOT
		(
			SUM(QTDE_ADESAO) FOR DATA_VENDA IN ('+@COLUNAS+')
		) AS PIVOTTABLE;'

PRINT (@SQL_STRING)

EXEC(@SQL_STRING)
