USE BRADESCARD

--DROP FUNCTION dbo.FILTRA_NUMEROS


CREATE FUNCTION dbo.FILTRA_NUMEROS(@STRING VARCHAR(100)) RETURNS VARCHAR(100) AS
BEGIN
	DECLARE @MAX INT, @CARAC CHAR(1), @NUM VARCHAR(100)
	SET @MAX = (SELECT Len(@STRING))
	SET @NUM = ''
	WHILE @MAX > 0
		Begin
			Set @CARAC = (Select UPPER(Right(Left(@STRING, Len(@STRING) - @MAX + 1), 1)))
					If IsNumeric(@CARAC) = 1
						Begin
							Set @NUM = @NUM + @CARAC
						End

			Set @MAX = @MAX - 1
		End
	RETURN @NUM
END

GO

Select DBO.FILTRA_NUMEROS('Adelmo de MORAIS 123 A1B2C3')