USE BRADESCARD

--DROP FUNCTION dbo.FILTRA_TEXTO


CREATE FUNCTION dbo.FILTRA_TEXTO(@STRING VARCHAR(100)) RETURNS VARCHAR(100) AS
BEGIN
	DECLARE @MAX INT, @CARAC CHAR(1), @TEXTO VARCHAR(100)
	SET @MAX = (SELECT Len(@STRING))
	SET @TEXTO = ''
	WHILE @MAX > 0
		Begin
			Set @CARAC = (Select UPPER(Right(Left(@STRING, Len(@STRING) - @MAX + 1), 1)))
					If NOT IsNumeric(@CARAC) = 1
						Begin
							Set @TEXTO = @TEXTO + @CARAC
						End

			Set @MAX = @MAX - 1
		End
	RETURN @TEXTO
END

GO

Select dbo.FILTRA_TEXTO('Adelmo de MORAIS 123 A1B2C3')