--@Autor: José Adelmo de Morais			@Data:01/08/2018
--@Atividade: Monitoria de vendas Bradescard
/*------------------------------------------------------------------------------------------------------*/
/* Parte 4 - Cria_Monitoria_Venda																		*/
/* Origem: alimentada diariamente pelo processo de importação com										*/
/* os Arquivos XLSX de consulta previa de todos os parceiros - Enviado todos os dias por; VICTOR DANIEL */ 
/* ARAUJO DE LIMA do Bradesco Cartoes - Email: victordaniel.lima@bradesco.com.br - Tel.:(11) 4831-1881  */    
/*------------------------------------------------------------------------------------------------------*/

USE BRADESCARD

DECLARE @DATA_MONITORIA AS DATE

SET @DATA_MONITORIA = '2019-07-24' --<<-- INFORME A DATA DE APURAÇÃO DA MONITORIA --]]

IF OBJECT_ID('BRADESCARD..MONITORIA_VENDA') IS NOT NULL
		BEGIN
			DROP TABLE MONITORIA_VENDA
		END

CREATE TABLE MONITORIA_VENDA
	(
		[CODIGO_PARCEIRO] INT,
		[DESCRICAO_PARCEIRO] VARCHAR(20),
		[CODIGO_LOJA] INT,
		[DESCRICAO_LOJA] VARCHAR(50),
		[DATA_VENDA] DATE, 
		[DIA_SEMANA_VENDA] VARCHAR(20),
		[QTDE_CONSULTA_PREVIA] FLOAT,
		[QTDE_PREVIA_APROVADA] FLOAT,
		[QTDE_PROPOSTA] FLOAT,
		[QTDE_ADESAO] FLOAT,
	)

INSERT INTO MONITORIA_VENDA

SELECT	VD.CODIGO_PARCEIRO,
		VD.DESCRICAO_PARCEIRO, 
		VD.CODIGO_LOJA,
		VD.DESCRICAO_LOJA,
		VD.DATA_VENDA,
		VD.DIA_SEMANA_VENDA,
		CONVERT(FLOAT,VD.QTDE_CONSULTA_PREVIA) AS QTDE_CONSULTA_PREVIA ,
		CONVERT(FLOAT,VD.QTDE_PREVIA_APROVADA) AS QTDE_PREVIA_APROVADA,
		CONVERT(FLOAT,VD.QTDE_PROPOSTA) AS QTDE_PROPOSTA,
		CONVERT(FLOAT,VD.QTDE_ADESAO) AS QTDE_ADESAO
FROM VENDA_DIARIA AS VD
LEFT JOIN TB_LOJA AS L	ON L.CODIGO_PARCEIRO = VD.CODIGO_PARCEIRO AND L.CODIGO_LOJA_NOVOFRONT = VD.CODIGO_LOJA
WHERE DATA_VENDA  BETWEEN	(SELECT DATEADD(MONTH,-3, @DATA_MONITORIA))	AND	(SELECT MAX(@DATA_MONITORIA))
	  AND L.SISTEMA_ORIGINACAO LIKE '%NOVO FRONT%'
	  AND L.ATIVACAO_LOJA = 'S'	
	  AND L.STATUS_LOJA	  = 'ABERTA'
	  

SELECT	DESCRICAO_PARCEIRO,
		CODIGO_LOJA,
		DATA_VENDA,
		DIA_SEMANA_VENDA,
		QTDE_CONSULTA_PREVIA,
		QTDE_PREVIA_APROVADA,
		QTDE_PROPOSTA,
		QTDE_ADESAO
		FROM MONITORIA_VENDA 
ORDER BY DESCRICAO_PARCEIRO,CODIGO_LOJA,DATA_VENDA


