--@Autor: José Adelmo de Morais			@Data:02/08/2018
--@Atividade: Monitoria de vendas Bradescard
/*------------------------------------------------------------------------------------------------------*/
/* Parte 5 - MEDIA_VENDA_DIA_SEMANA																		*/
/* Origem: alimentada diariamente pelo processo de importação com										*/
/* os Arquivos XLSX de consulta previa de todos os parceiros - Enviado todos os dias por; VICTOR DANIEL */ 
/* ARAUJO DE LIMA do Bradesco Cartoes - Email: victordaniel.lima@bradesco.com.br - Tel.:(11) 4831-1881  */    
/*------------------------------------------------------------------------------------------------------*/

USE BRADESCARD

IF OBJECT_ID('BRADESCARD..MEDIA_VENDA_DIA_SEMANA') IS NOT NULL
		BEGIN
			DROP TABLE MEDIA_VENDA_DIA_SEMANA
		END

CREATE TABLE MEDIA_VENDA_DIA_SEMANA
	(
		[CODIGO_PARCEIRO]			VARCHAR(4),
		[DESCRICAO_PARCEIRO]		VARCHAR(15),
		[CODIGO_LOJA]				VARCHAR(8),
		[MEDIA_TRES_MESES_SEGUNDA]	FLOAT(3), 
		[MEDIA_TRES_MESES_TERCA]	FLOAT(3), 
		[MEDIA_TRES_MESES_QUARTA]	FLOAT(3), 
		[MEDIA_TRES_MESES_QUINTA]	FLOAT(3), 
		[MEDIA_TRES_MESES_SEXTA]	FLOAT(3), 
		[MEDIA_TRES_MESES_SABADO]	FLOAT(3), 
		[MEDIA_TRES_MESES_DOMINGO]	FLOAT(3)
	)

INSERT INTO MEDIA_VENDA_DIA_SEMANA
SELECT
		MV.CODIGO_PARCEIRO,
		MV.DESCRICAO_PARCEIRO,
		MV.CODIGO_LOJA,
		SUM(CASE WHEN DIA_SEMANA_VENDA = '2-SEGUNDA-FEIRA' THEN QTDE_CONSULTA_PREVIA END)
		/COUNT(CASE WHEN DIA_SEMANA_VENDA = '2-SEGUNDA-FEIRA' THEN QTDE_CONSULTA_PREVIA END) AS MEDIA_TRES_MESES_SEGUNDA,
		SUM(CASE WHEN DIA_SEMANA_VENDA = '3-TERÇA-FEIRA' THEN QTDE_CONSULTA_PREVIA END)
		/COUNT(CASE WHEN DIA_SEMANA_VENDA = '3-TERÇA-FEIRA' THEN QTDE_CONSULTA_PREVIA END) AS MEDIA_TRES_MESES_TERCA,
		SUM(CASE WHEN DIA_SEMANA_VENDA = '4-QUARTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END)
		/COUNT(CASE WHEN DIA_SEMANA_VENDA = '4-QUARTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END) AS MEDIA_TRES_MESES_QUARTA,
		SUM(CASE WHEN DIA_SEMANA_VENDA = '5-QUINTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END)
		/COUNT(CASE WHEN DIA_SEMANA_VENDA = '5-QUINTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END) AS MEDIA_TRES_MESES_QUINTA,
		SUM(CASE WHEN DIA_SEMANA_VENDA = '6-SEXTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END)
		/COUNT(CASE WHEN DIA_SEMANA_VENDA = '6-SEXTA-FEIRA' THEN QTDE_CONSULTA_PREVIA END) AS MEDIA_TRES_MESES_SEXTA,
		SUM(CASE WHEN DIA_SEMANA_VENDA = '7-SABADO' THEN QTDE_CONSULTA_PREVIA END)
		/COUNT(CASE WHEN DIA_SEMANA_VENDA = '7-SABADO' THEN QTDE_CONSULTA_PREVIA END) AS MEDIA_TRES_MESES_SABADO,
		SUM(CASE WHEN DIA_SEMANA_VENDA = '1-DOMINGO' THEN QTDE_CONSULTA_PREVIA END)
		/COUNT(CASE WHEN DIA_SEMANA_VENDA = '1-DOMINGO' THEN QTDE_CONSULTA_PREVIA END) AS MEDIA_TRES_MESES_DOMINGO

FROM MONITORIA_VENDA MV
LEFT JOIN TB_LOJA AS L	ON L.CODIGO_PARCEIRO = MV.CODIGO_PARCEIRO AND L.CODIGO_LOJA_NOVOFRONT = MV.CODIGO_LOJA										
WHERE DATA_VENDA <= (SELECT DATEADD(WEEK, -1,MAX(DATA_VENDA)) FROM MONITORIA_VENDA )
AND  L.FAZER_CONTATO = 'S'	--ALTERADO AQUI
GROUP BY MV.CODIGO_PARCEIRO,MV.DESCRICAO_PARCEIRO,MV.CODIGO_LOJA
ORDER BY CODIGO_LOJA

--SELECT * FROM MEDIA_VENDA_DIA_SEMANA
---------------------------------------------------------------------------------------------------------------
/* Parte 5.1 - CALCULA_VARIACAO_MEDIA																		*/
---------------------------------------------------------------------------------------------------------------

IF OBJECT_ID('BRADESCARD..CALCULA_VARIACAO_MEDIA') IS NOT NULL
		BEGIN
			DROP TABLE CALCULA_VARIACAO_MEDIA
		END

CREATE TABLE CALCULA_VARIACAO_MEDIA
	(
		[DIA_SEMANA_VENDA]		VARCHAR(20),
		[CODIGO_PARCEIRO]		VARCHAR(8),
		[DESCRICAO_PARCEIRO]	VARCHAR(15),
		[CODIGO_LOJA]			VARCHAR(8),
		[QTDE_VENDA_DIA]		INT, 
		[MEDIA_DO_DIA_SEMANA]	FLOAT(5), 
	)


INSERT INTO CALCULA_VARIACAO_MEDIA
SELECT	MV.DIA_SEMANA_VENDA,
		MV.CODIGO_PARCEIRO,
		MV.DESCRICAO_PARCEIRO,
		MV.CODIGO_LOJA,
		MV.QTDE_CONSULTA_PREVIA AS QTDE_VENDA_DIA,
		CASE 
			WHEN DIA_SEMANA_VENDA = '2-SEGUNDA-FEIRA' THEN DS.MEDIA_TRES_MESES_SEGUNDA
			WHEN DIA_SEMANA_VENDA = '3-TERÇA-FEIRA'	THEN DS.MEDIA_TRES_MESES_TERCA
			WHEN DIA_SEMANA_VENDA = '4-QUARTA-FEIRA'	THEN DS.MEDIA_TRES_MESES_QUARTA
			WHEN DIA_SEMANA_VENDA = '5-QUINTA-FEIRA'	THEN DS.MEDIA_TRES_MESES_QUINTA
			WHEN DIA_SEMANA_VENDA = '6-SEXTA-FEIRA'	THEN DS.MEDIA_TRES_MESES_SEXTA
			WHEN DIA_SEMANA_VENDA = '7-SABADO'		THEN DS.MEDIA_TRES_MESES_SABADO
			WHEN DIA_SEMANA_VENDA = '1-DOMINGO'		THEN DS.MEDIA_TRES_MESES_DOMINGO
		END AS MEDIA_DO_DIA_SEMANA

FROM MONITORIA_VENDA AS MV
INNER JOIN MEDIA_VENDA_DIA_SEMANA AS DS ON MV.CODIGO_PARCEIRO = DS.CODIGO_PARCEIRO AND MV.CODIGO_LOJA = DS.CODIGO_LOJA
WHERE DATA_VENDA = (SELECT MAX([DATA_VENDA]) FROM MONITORIA_VENDA)

--SELECT * FROM CALCULA_VARIACAO_MEDIA
--ORDER BY CODIGO_LOJA


---------------------------------------------------------------------------------------------------------------
/* Parte 5.2 - ABAIXO_MEDIA																					*/
---------------------------------------------------------------------------------------------------------------

IF OBJECT_ID('BRADESCARD..ABAIXO_MEDIA') IS NOT NULL
		BEGIN
			DROP TABLE ABAIXO_MEDIA
		END

CREATE TABLE ABAIXO_MEDIA
	(
		[CODIGO_PARCEIRO]			INT,
		[DESCRICAO_PARCEIRO]		VARCHAR(15),
		[CODIGO_LOJA]				INT,		
		[DESCRICAO_LOJA]			VARCHAR(50),
		[DIA_SEMANA_VENDA]			VARCHAR(20),
		[DATA_VENDA]				DATE,
		[QTDE_VENDA_DIARIA]			INT,
		[MEDIA_DO_DIA_SEMANA]		FLOAT(5),
		[MEDIA_DIARIA_TRIMESTRAL]	FLOAT(5),
		[ENDERECO_LOJA]				VARCHAR(100),
		[BAIRRO_LOJA]				VARCHAR(60),
		[CIDADE_LOJA]				VARCHAR(50),
		[UF_LOJA]					VARCHAR(2),
		[CEP_LOJA]					VARCHAR(9),
		[TELEFONE_LOJA]				VARCHAR(16),
		[CELULAR_LOJA]				VARCHAR(16),
		[EMAIL_LOJA]				VARCHAR(70),
		[ATIVACAO_LOJA]				VARCHAR(1)
	)


INSERT INTO ABAIXO_MEDIA

SELECT A.*  FROM
(
SELECT	CVM.CODIGO_PARCEIRO,
		CVM.DESCRICAO_PARCEIRO,
		CVM.CODIGO_LOJA,
		L.DESCRICAO_LOJA,
		CVM.DIA_SEMANA_VENDA,
		(SELECT MAX([DATA_VENDA]) FROM MONITORIA_VENDA) AS DATA_VENDA,
		CVM.QTDE_VENDA_DIA,
		CVM.MEDIA_DO_DIA_SEMANA,
		CASE
			WHEN CVM.MEDIA_DO_DIA_SEMANA <= 0 
			AND QTDE_VENDA_DIA <= 0 THEN 
			0
			WHEN CVM.MEDIA_DO_DIA_SEMANA <= 0
			AND QTDE_VENDA_DIA > 0 THEN
			CVM.QTDE_VENDA_DIA/CVM.QTDE_VENDA_DIA
			ELSE CVM.QTDE_VENDA_DIA/CVM.MEDIA_DO_DIA_SEMANA
		END  AS MEDIA_DIARIA_TRIMESTRAL,
		L.ENDERECO_LOJA,
		L.BAIRRO_LOJA,
		L.CIDADE_LOJA,
		L.UF_LOJA,
		L.CEP_LOJA,
		L.TELEFONE_LOJA,
		L.CELULAR_LOJA,
		L.EMAIL_LOJA,
		L.ATIVACAO_LOJA
FROM CALCULA_VARIACAO_MEDIA AS CVM
INNER JOIN TB_LOJA AS L ON CVM.CODIGO_PARCEIRO = L.CODIGO_PARCEIRO  AND CVM.CODIGO_LOJA = L.CODIGO_LOJA_NOVOFRONT
) AS A
WHERE A.MEDIA_DIARIA_TRIMESTRAL < 0.5
ORDER BY A.MEDIA_DIARIA_TRIMESTRAL, A.CODIGO_LOJA

--SELECT * FROM ABAIXO_MEDIA

---------------------------------------------------------------------------------------------------------------
/* Parte 5.3 - HISTORICO_VENDAS																				*/
---------------------------------------------------------------------------------------------------------------

SELECT	MV.DATA_VENDA,
		dbo.DIA_DA_SEMANA(MV.DATA_VENDA) AS DIA_SEMANA_VENDA,
		MV.DESCRICAO_PARCEIRO,
		MV.CODIGO_LOJA,
		AM.DESCRICAO_LOJA,
		MV.QTDE_CONSULTA_PREVIA,
		MV.QTDE_PREVIA_APROVADA,
		MV.QTDE_PROPOSTA,
		MV.QTDE_ADESAO
FROM ABAIXO_MEDIA AS AM
INNER JOIN MONITORIA_VENDA AS MV ON AM.CODIGO_PARCEIRO = MV.CODIGO_PARCEIRO
AND AM.CODIGO_LOJA = MV.CODIGO_LOJA

ORDER BY DATA_VENDA DESC

--------------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM ABAIXO_MEDIA