--DROP TABLE #AMEX_AFILIADOR
CREATE TABLE #AMEX_AFILIADOR(
	CD_AFILIADOR	BIGINT,
	DS_AFILIADOR	VARCHAR(100)
)


BULK INSERT #AMEX_AFILIADOR
FROM 'G:\1 - Amex\18 - Junho - 2017\AFILIADOR.txt' 
WITH(CODEPAGE = 'ACP', FIRSTROW = 2, FIELDTERMINATOR = ';')
--(350 row(s) affected)


DROP TABLE AMEX_AFILIADOR
SELECT
	CD_AFILIADOR,
	LTRIM(RTRIM(DS_AFILIADOR))	AS DS_AFILIADOR,
	CONVERT(DATE,GETDATE())		AS DT_IMPORTACAO
INTO
	AMEX_AFILIADOR
FROM
	#AMEX_AFILIADOR
--(14 row(s) affected)

UPDATE AMEX_AFILIADOR SET DS_AFILIADOR = 'GLOBAL PAYMENT' WHERE DS_AFILIADOR = 'GLOBAL·PAYMENT'


SELECT * FROM AMEX_AFILIADOR