USE DB_QUINTO_ANDAR
SELECT 
	ROW_NUMBER() OVER (PARTITION BY HR_HORA ORDER BY DT_DATA ASC) AS ORDEM,
	 RET.DT_DATA
	,RET.HR_HORA
	,SUM(CASE WHEN TAB.NM_ALO		='SIM'	THEN 1	ELSE 0 END) AS NR_ALO
	,SUM(CASE WHEN TAB.NM_SUCESSO	='SIM'	THEN 1	ELSE 0 END) AS NR_VENDA	
	,CASE SUM(CASE WHEN TAB.NM_ALO	='SIM'	THEN 1	ELSE 0 END)
		WHEN 0 THEN 0 
	 ELSE
		CONVERT(DECIMAL(12,02),CONVERT(DECIMAL(12,02),SUM(CASE WHEN TAB.NM_SUCESSO ='SIM'	THEN 1	ELSE 0 END)) / CONVERT(DECIMAL(12,02),SUM(CASE WHEN TAB.NM_ALO ='SIM'	THEN 1	ELSE 0 END)))
	END AS VL_PORCENTUAL_CONVERSAO
	,CONVERT(DECIMAL(12,02),CONVERT(DECIMAL(12,02),SUM(CASE WHEN TAB.NM_ID	= 6	THEN 1	ELSE 0 END)) / CONVERT(DECIMAL(12,02),COUNT(*))) AS VL_PORCENTUAL_BAD_NUMBER
FROM [DB_QUINTO_ANDAR].[DBO].[TB_OLOS_O_RETORNO_IS] AS RET
INNER JOIN [DBO].[TB_DP_ARVORE_TABULACAO_IS]		AS TAB
	ON RET.[NM_DISPOSITIONID] = TAB.NM_ID
GROUP BY 
	 RET.DT_DATA
	,RET.HR_HORA