USE BRADESCARD

DECLARE @TABELA VARCHAR(200)
DECLARE @QTD_COLUNA INT
DECLARE @STRING_COLUNA VARCHAR(8000)
DECLARE @COL VARCHAR(200)
DECLARE @COMANDO_SQL VARCHAR(200)

SET @TABELA = '''Indicadores Diarios$''' -- NOME DA TABELA 
SET @QTD_COLUNA = (SELECT Max(ORDINAL_POSITION)
                  FROM   INFORMATION_SCHEMA.COLUMNS CL
                  WHERE  CL.TABLE_NAME = @TABELA)

			select (@QTD_COLUNA)

DECLARE @INDEX INTEGER

SET @INDEX = 0

WHILE @INDEX < @QTD_COLUNA
  BEGIN
      SET @COL = (SELECT COLUMN_NAME
                  FROM   INFORMATION_SCHEMA.COLUMNS CL
                  WHERE  CL.TABLE_NAME = @TABELA
                         AND ORDINAL_POSITION = @INDEX)

      IF @STRING_COLUNA IS NULL
        BEGIN
            SET @STRING_COLUNA = @COL
        END
      ELSE
        BEGIN
            SET @STRING_COLUNA = ( @STRING_COLUNA + ',' + @COL )
        END

      SET @INDEX = @INDEX + 1
	  SET @COMANDO_SQL = ('SELECT ' + @STRING_COLUNA + ' FROM ' + @TABELA)
	  SELECT(@COMANDO_SQL)
  END

 

 