
use BRADESCARD

insert into gru3wvamexdb1.bra_solucoes_pdv.dbo.VENDA_DIARIA_NOVOFRONT
select CODIGO_PARCEIRO,CODIGO_LOJA,null,null,null,'CONSULTA PRÉVIA', sum(QTDE_CONSULTA_PREVIA), DATA_VENDA, DATA_IMPORTACAO_ARQUIVO, 'XLS'
 from VENDA_DIARIA group by CODIGO_PARCEIRO,CODIGO_LOJA,DATA_VENDA,DATA_IMPORTACAO_ARQUIVO

insert into gru3wvamexdb1.bra_solucoes_pdv.dbo.VENDA_DIARIA_NOVOFRONT
 select CODIGO_PARCEIRO,CODIGO_LOJA,null,null,null,'PRÉVIA APROVADA', sum(QTDE_PREVIA_APROVADA), DATA_VENDA, DATA_IMPORTACAO_ARQUIVO, 'XLS'
  from VENDA_DIARIA group by CODIGO_PARCEIRO,CODIGO_LOJA,DATA_VENDA,DATA_IMPORTACAO_ARQUIVO

insert into gru3wvamexdb1.bra_solucoes_pdv.dbo.VENDA_DIARIA_NOVOFRONT
 select CODIGO_PARCEIRO,CODIGO_LOJA,null,null,null,'PROPOSTA', sum(QTDE_PROPOSTA), DATA_VENDA, DATA_IMPORTACAO_ARQUIVO, 'XLS'
 from VENDA_DIARIA group by CODIGO_PARCEIRO,CODIGO_LOJA,DATA_VENDA,DATA_IMPORTACAO_ARQUIVO

insert into gru3wvamexdb1.bra_solucoes_pdv.dbo.VENDA_DIARIA_NOVOFRONT
 select CODIGO_PARCEIRO,CODIGO_LOJA,null,null,null,'ADESÃO', sum( QTDE_ADESAO), DATA_VENDA, DATA_IMPORTACAO_ARQUIVO, 'XLS'
 from VENDA_DIARIA group by CODIGO_PARCEIRO,CODIGO_LOJA,DATA_VENDA,DATA_IMPORTACAO_ARQUIVO


 


 

 select * from VENDA_DIARIA_NOVOFRONT