
USE BRA_SOLUCOES_PDV


--====================INPORT ARQUIVO TXT==============================================
EXECUTE INPORT_TXT

--====================INPORT ARQUIVO EXCEL TODOS======================================
EXECUTE INPORT_XLS

--====================SELECT DE VALIDAÇÃO=============================================
SELECT DISTINCT ARQUIVO_IMPORTACAO, DATA_ACAO AS 'DATAS IMPORTADAS' 
FROM VENDA_DIARIA_NOVOFRONT 
ORDER BY DATA_ACAO DESC

--====================INPORT ARQUIVO EXCEL POR PROCESSO===============================
EXECUTE INPORT_XLS_ADESAO
EXECUTE INPORT_XLS_CONSULTA_PREVIA
EXECUTE INPORT_XLS_PREVIA_APROVADA
EXECUTE INPORT_XLS_PROPOSTA

--==================== INPORT ARQUIVO EXCEL POR PARCEIRO E PROCESSO ====================

--==================== ANGELONI =================================================

EXECUTE INPORT_XLS_CONSULTA_PREVIA_ANGELONI
EXECUTE INPORT_XLS_PREVIA_APROVADA_ANGELONI
EXECUTE INPORT_XLS_PROPOSTA_ANGELONI
EXECUTE INPORT_XLS_ADESAO_ANGELONI

--==================== COOP =====================================================

EXECUTE INPORT_XLS_CONSULTA_PREVIA_COOP
EXECUTE INPORT_XLS_PREVIA_APROVADA_COOP
EXECUTE INPORT_XLS_PROPOSTA_COOP
EXECUTE INPORT_XLS_ADESAO_COOP

--==================== LASA =====================================================

EXECUTE INPORT_XLS_CONSULTA_PREVIA_LASA
EXECUTE INPORT_XLS_PREVIA_APROVADA_LASA
EXECUTE INPORT_XLS_PROPOSTA_LASA
EXECUTE INPORT_XLS_ADESAO_LASA

--==================== MAKRO ====================================================

EXECUTE INPORT_XLS_CONSULTA_PREVIA_MAKRO
EXECUTE INPORT_XLS_PREVIA_APROVADA_MAKRO
EXECUTE INPORT_XLS_PROPOSTA_MAKRO
EXECUTE INPORT_XLS_ADESAO_MAKRO

--==================== SODIMAC ==================================================

EXECUTE INPORT_XLS_CONSULTA_PREVIA_SODIMAC
EXECUTE INPORT_XLS_PREVIA_APROVADA_SODIMAC
EXECUTE INPORT_XLS_PROPOSTA_SODIMAC
EXECUTE INPORT_XLS_ADESAO_SODIMAC










