--- CRIAÇÃO DA TABELA TEMPORÁRIA
IF OBJECT_ID('TEMPDB..#CONTAS') IS NOT NULL
	BEGIN
		DROP TABLE #CONTAS
	END;
	

CREATE TABLE #CONTAS
	( 
	ST_CONTA VARCHAR(1),
	CONTA_2	 VARCHAR(1),
	B2_CONTA VARCHAR(1)
	)

INSERT INTO #CONTAS
SELECT DISTINCT  ST_CONTA,CONTA_2,B2_CONTA
FROM TB_AUDIT 

------------------------------------------------------

--- CRIAÇÃO DA TABELA TEMPORÁRIA
IF OBJECT_ID('TEMPDB..#TEMP_SEIS_MESES') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_SEIS_MESES
	END;
	

CREATE TABLE #TEMP_SEIS_MESES
	( 
	ST_CONTA VARCHAR(1),
	CONTA_2	 VARCHAR(1),
	B2_CONTA VARCHAR(1),
	QTD_CONTA INT
	)

INSERT INTO #TEMP_SEIS_MESES
SELECT 
	ST_CONTA, 
	CONTA_2,
	B2_CONTA,
	COUNT(CONTA) QTD_CONTA
FROM TB_AUDIT 
WHERE DT_ULT_CMPR  > CONVERT(DATE,DATEADD(MONTH,-6, GETDATE())) AND DT_B1_CONTA < CONVERT(DATE,GETDATE()) 
GROUP BY ST_CONTA,CONTA_2,B2_CONTA


--------------------------------------------------------------------

--- CRIAÇÃO DA TABELA TEMPORÁRIA
IF OBJECT_ID('TEMPDB..#TEMP_UM_ANO') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_UM_ANO
	END;

CREATE TABLE #TEMP_UM_ANO
	( 
	ST_CONTA VARCHAR(1),
	CONTA_2	 VARCHAR(1),
	B2_CONTA VARCHAR(1),
	QTD_CONTA INT
	)

INSERT INTO #TEMP_UM_ANO
SELECT 
	ST_CONTA, 
	CONTA_2,
	B2_CONTA,
	COUNT(CONTA) QTD_CONTA
FROM TB_AUDIT 
WHERE DT_ULT_CMPR >= CONVERT(DATE,DATEADD(YEAR,-1, GETDATE())) AND DT_B1_CONTA <= CONVERT(DATE,DATEADD(MONTH,-6, GETDATE()))
GROUP BY ST_CONTA,CONTA_2,B2_CONTA


--------------------------------------------------------------------
--- CRIAÇÃO DA TABELA TEMPORÁRIA
IF OBJECT_ID('TEMPDB..#TEMP_DOIS_ANO') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_DOIS_ANO
	END;


CREATE TABLE #TEMP_DOIS_ANO
	( 
	ST_CONTA VARCHAR(1),
	CONTA_2	 VARCHAR(1),
	B2_CONTA VARCHAR(1),
	QTD_CONTA INT
	)

INSERT INTO #TEMP_DOIS_ANO
SELECT 
	ST_CONTA, 
	CONTA_2,
	B2_CONTA,
	COUNT(CONTA) QTD_CONTA
FROM TB_AUDIT 
WHERE DT_ULT_CMPR >= CONVERT(DATE,DATEADD(YEAR,-2, GETDATE())) AND DT_B1_CONTA < CONVERT(DATE,DATEADD(YEAR,-1, GETDATE()))
GROUP BY ST_CONTA,CONTA_2,B2_CONTA


--------------------------------------------------------------------
--- CRIAÇÃO DA TABELA TEMPORÁRIA
IF OBJECT_ID('TEMPDB..#TEMP_TRES_ANO') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_TRES_ANO
	END;

CREATE TABLE #TEMP_TRES_ANO
	( 
	ST_CONTA VARCHAR(1),
	CONTA_2	 VARCHAR(1),
	B2_CONTA VARCHAR(1),
	QTD_CONTA INT
	)

INSERT INTO #TEMP_TRES_ANO
SELECT 
	ST_CONTA, 
	CONTA_2,
	B2_CONTA, 
	COUNT(CONTA) QTD_CONTA
FROM TB_AUDIT 
WHERE DT_ULT_CMPR >= CONVERT(DATE,DATEADD(YEAR,-3, GETDATE())) AND DT_B1_CONTA < CONVERT(DATE,DATEADD(YEAR,-2, GETDATE()))
GROUP BY ST_CONTA,CONTA_2,B2_CONTA


--------------------------------------------------------------------
--- CRIAÇÃO DA TABELA TEMPORÁRIA
IF OBJECT_ID('TEMPDB..#TEMP_MAIOR_TRES_ANO') IS NOT NULL
	BEGIN
		DROP TABLE #TEMP_MAIOR_TRES_ANO
	END;

CREATE TABLE #TEMP_MAIOR_TRES_ANO
	( 
	ST_CONTA VARCHAR(1),
	CONTA_2	 VARCHAR(1),
	B2_CONTA VARCHAR(1),
	QTD_CONTA INT
	)

INSERT INTO #TEMP_MAIOR_TRES_ANO
SELECT 
	ST_CONTA, 
	CONTA_2,
	B2_CONTA,  
	COUNT(CONTA) QTD_CONTA
FROM TB_AUDIT 
WHERE DT_ULT_CMPR < CONVERT(DATE,DATEADD(YEAR,-3, GETDATE()))
GROUP BY ST_CONTA,CONTA_2,B2_CONTA




----------------QUANTIDADE DE CONTAS QUE NÃO TRANSACIONARAM - A DATA DA ULTIMA COMPRA É MENOR QUE 6 MESES, 1 ANO, 2 ANOS E 3 ANOS-------------------------------------------------

SELECT	C.ST_CONTA,
		C.CONTA_2,
		C.B2_CONTA,
		SEISMESES.QTD_CONTA		AS MENOS_DE_SEIS_MESES,
		UMANO.QTD_CONTA			AS SEIS_MESES_A_UM_ANO,
		DOISANO.QTD_CONTA		AS UM_ANO_A_DOIS,
		TRESANO.QTD_CONTA		AS DOIS_ANOS_A_TRES,
		MAIORTRESANO.QTD_CONTA	AS MAIS_DE_TRES_ANO
	 FROM #CONTAS						AS C
	 LEFT JOIN #TEMP_SEIS_MESES			AS SEISMESES	ON SEISMESES.ST_CONTA		= C.ST_CONTA
	 LEFT JOIN #TEMP_UM_ANO				AS UMANO		ON UMANO.ST_CONTA			= C.ST_CONTA
	 LEFT JOIN #TEMP_DOIS_ANO			AS DOISANO		ON DOISANO.ST_CONTA			= C.ST_CONTA
	 LEFT JOIN #TEMP_TRES_ANO			AS TRESANO		ON TRESANO.ST_CONTA			= C.ST_CONTA
	 LEFT JOIN #TEMP_MAIOR_TRES_ANO	AS MAIORTRESANO	ON MAIORTRESANO.ST_CONTA		= C.ST_CONTA



