

SELECT TOP 1000
		SUBSTRING(DADOS, 1, 3)		AS ORG,
		SUBSTRING(DADOS, 4, 3)		AS LOGO, 
		SUBSTRING(DADOS, 7, 19)		AS CONTA,
		SUBSTRING(DADOS, 26, 1)		AS ST_CONTA,
		SUBSTRING(DADOS, 27, 1)		AS CONTA_2,
		SUBSTRING(DADOS, 28, 8)		AS DT_B1_CONTA,
		SUBSTRING(DADOS, 36, 1)		AS B2_CONTA,
		SUBSTRING(DADOS, 37, 8)		AS DT_B2_CONTA,
		SUBSTRING(DADOS, 45, 8)		AS DT_ULT_CMPR,
		SUBSTRING(DADOS, 53, 3)		AS COL_REL,
		SUBSTRING(DADOS, 56, 20)	AS CAMINHO_TABELA,
		SUBSTRING(DADOS, 76, 20)	AS CAMINHO_TAB,
		SUBSTRING(DADOS, 96, 1)		AS CAMINHO,
		SUBSTRING(DADOS, 97, 19)	AS NUM_CARTAO,
		SUBSTRING(DADOS, 116, 1)	AS TIT_CARTAO,
		SUBSTRING(DADOS, 117, 1)	AS ST_CARTAO,
		SUBSTRING(DADOS, 118, 1)	AS BLQ_CARTAO,
		SUBSTRING(DADOS, 119, 8)	AS DT_BLK_CARTAO,
		SUBSTRING(DADOS, 127, 8)	AS DT_DESBLOQ,
		SUBSTRING(DADOS, 135, 1)	AS CAM_CARTAO,
		SUBSTRING(DADOS, 136, 8)	AS DT_ABERT_CONTA,
		SUBSTRING(DADOS, 144, 8)	AS DT_CONTA_ALTER
FROM [dbo].[AUDIT237]

