 
 USE TESTES

 CREATE TABLE RESUMO 
	(
	ORG				VARCHAR(3),
	LOGO			VARCHAR(3),
	CONTA			VARCHAR(19),
	ST_CONTA		VARCHAR(1),
	CONTA_2			VARCHAR(1),
	DT_B1_CONTA		VARCHAR(8),
	B2_CONTA		VARCHAR(1),
	DT_B2_CONTA		VARCHAR(8),
	DT_ULT_CMPR		VARCHAR(8),
	COL_REL			VARCHAR(3),
	CAMINHO_TABELA	VARCHAR(20),
	CAMINHO_TAB		VARCHAR(20),
	CAMINHO			VARCHAR(1),
	NUM_CARTAO		VARCHAR(19),
	TIT_CARTAO		VARCHAR(1),
	ST_CARTAO		VARCHAR(1),
	BLQ_CARTAO		VARCHAR(1),
	DT_BLK_CARTAO	VARCHAR(8),
	DT_DESBLOQ		VARCHAR(8),
	CAM_CARTAO		VARCHAR(1),
	DT_ABERT_CONTA	VARCHAR(8),
	DT_CONTA_ALTER	VARCHAR(8)
	)

INSERT INTO RESUMO
SELECT 
		SUBSTRING(DADOS, 1, 3)		AS ORG,
		SUBSTRING(DADOS, 4, 3)		AS LOGO, 
		SUBSTRING(DADOS, 7, 19)		AS CONTA,
		SUBSTRING(DADOS, 26, 1)		AS ST_CONTA,
		SUBSTRING(DADOS, 27, 1)		AS CONTA_2,
		SUBSTRING(DADOS, 28, 8)		AS DT_B1_CONTA,
		SUBSTRING(DADOS, 36, 1)		AS B2_CONTA,
		SUBSTRING(DADOS, 37, 8)		AS DT_B2_CONTA,
		SUBSTRING(DADOS, 45, 8)		AS DT_ULT_CMPR,
		SUBSTRING(DADOS, 53, 3)		AS COL_REL,
		SUBSTRING(DADOS, 56, 20)	AS CAMINHO_TABELA,
		SUBSTRING(DADOS, 76, 20)	AS CAMINHO_TAB,
		SUBSTRING(DADOS, 96, 1)		AS CAMINHO,
		SUBSTRING(DADOS, 97, 19)	AS NUM_CARTAO,
		SUBSTRING(DADOS, 116, 1)	AS TIT_CARTAO,
		SUBSTRING(DADOS, 117, 1)	AS ST_CARTAO,
		SUBSTRING(DADOS, 118, 1)	AS BLQ_CARTAO,
		SUBSTRING(DADOS, 119, 8)	AS DT_BLK_CARTAO,
		SUBSTRING(DADOS, 127, 8)	AS DT_DESBLOQ,
		SUBSTRING(DADOS, 135, 1)	AS CAM_CARTAO,
		SUBSTRING(DADOS, 136, 8)	AS DT_ABERT_CONTA,
		SUBSTRING(DADOS, 144, 8)	AS DT_CONTA_ALTER
FROM [dbo].[AUDIT237]


SELECT	ST_CONTA,
		CONTA_2,
		B2_CONTA,
		COUNT (CONTA) AS QTDE_CONTAS
FROM RESUMO
GROUP BY ST_CONTA,CONTA_2,B2_CONTA