

SELECT  
	L.REGIONAL,
	P.CODIGO_PARCEIRO,
	L.CODIGO_LOJA_NOVOFRONT,
	CODIGO_PROMOTOR,
	VDN.DATA_ACAO,
	ISNULL(SUM (CASE WHEN DESCRITIVO = 'ENVIADO CONSULTA PREVIA'	OR DESCRITIVO = 'CONSULTA PRÉVIA'   THEN QUANTIDADE END),0) AS QTD_CONSULTA_PREVIA,
	ISNULL(SUM (CASE WHEN DESCRITIVO = 'APROVADO CONSULTA PREVIA'	OR DESCRITIVO = 'PRÉVIA APROVADA'	THEN QUANTIDADE END),0) AS QTD_PREVIA_APROVADA,
	ISNULL(SUM (CASE WHEN DESCRITIVO = 'EM DIGITAÇÃO'				OR DESCRITIVO = 'PROPOSTA'			THEN QUANTIDADE END),0) AS QTD_PROPOSTA,
	ISNULL(SUM (CASE WHEN DESCRITIVO = 'CONTAS APROVADAS'			OR DESCRITIVO = 'ADESÃO'			THEN QUANTIDADE END),0) AS QTD_ADESAO
FROM VENDA_DIARIA_NOVOFRONT VDN 
LEFT JOIN LOJA L ON VDN.CODIGO_LOJA = L.CODIGO_LOJA_NOVOFRONT
LEFT JOIN PARCEIRO P ON VDN.CODIGO_PARCEIRO = P.CODIGO_PARCEIRO
WHERE DESCRITIVO  IN ('ENVIADO CONSULTA PREVIA','CONSULTA PRÉVIA','APROVADO CONSULTA PREVIA','PRÉVIA APROVADA','EM DIGITAÇÃO','PROPOSTA','CONTAS APROVADAS','ADESÃO')
	AND L.SISTEMA_ORIGINACAO LIKE '%NOVO FRONT%'
	AND L.ATIVACAO_LOJA = 'S'	
	AND L.STATUS_LOJA	  = 'ABERTA'
GROUP BY L.REGIONAL,P.CODIGO_PARCEIRO,L.CODIGO_LOJA_NOVOFRONT,CODIGO_PROMOTOR,VDN.DATA_ACAO
ORDER BY 1 DESC



