USE NETSET

-- SELECIONA A DATA ATUAL --
SELECT GETDATE()

-- SELECIONA DIA DA SEMANA EM FORMATO NÚMERO --
SELECT DATEPART(WEEKDAY,GETDATE())


 -- SELECIONA DADOS DE 11 DIAS ATRÁS ATÉ A DATA ATUAL --
SELECT * 
FROM [dbo].[AMEX_SEDATA_MENSAL] 
WHERE DT_AFILIACAO BETWEEN DATEADD(DD,-11,GETDATE()) AND GETDATE()



SELECT CAST(GETDATE() AS DATE)
SELECT CAST(GETDATE() AS TIME)

SELECT DATEPART(DD,GETDATE())
SELECT DATEPART(MM,GETDATE())
SELECT DATEPART(YY,GETDATE())


SELECT DAY(GETDATE())
SELECT MONTH(GETDATE())
SELECT YEAR(GETDATE())


SELECT DATEADD(DD,10, GETDATE())
SELECT DATEADD(DD,-10, GETDATE())
SELECT DATEADD(MM,4, GETDATE())
SELECT DATEADD(MM,-4, GETDATE())
SELECT DATEADD(YY,3, GETDATE())
SELECT DATEADD(YY,-3, GETDATE())


SELECT DATEDIFF(DAY,'1985-06-12', GETDATE()) AS 'DIAS VIVIDOS';
SELECT DATEDIFF(DD,'1985-06-12', GETDATE()) AS 'DIAS VIVIDOS';

SELECT DATEDIFF(MONTH,'1985-06-12', GETDATE()) AS 'DIAS VIVIDOS';
SELECT DATEDIFF(MM,'1985-06-12', GETDATE()) AS 'MESES VIVIDOS';

SELECT DATEDIFF(YEAR,'1985-06-12', GETDATE()) AS 'DIAS VIVIDOS';
SELECT DATEDIFF(YY,'1985-06-12', GETDATE()) AS 'ANOS VIVIDOS';


