DECLARE @SKILLS VARCHAR(255)
SET @SKILLS = (SELECT DISTINCT
				COALESCE(
					(SELECT DISTINCT 'SKILLS ' +  CAST(NR_SKILL AS VARCHAR(10)) + ';' AS NR_SKILL
					 FROM DB_SAMSUNG.DBO.TB_SAMS_CMS_DESEMP_SERV_INTERV_GR_DIV_MIS_01 AS A
					 WHERE A.NR_SKILL  = CMS.NR_SKILL
					 ORDER BY NR_SKILL
					 FOR XML PATH(''), TYPE).value('.[1]', 'VARCHAR(MAX)'), '')  AS NR_SKILL    
			  FROM 
				DB_SAMSUNG.DBO.TB_SAMS_CMS_DESEMP_SERV_INTERV_GR_DIV_MIS_01 AS CMS
			  WHERE 
				NM_CELULA_NOME = 'INSS HOTLINE')

SELECT  
	 DT_DATA
    ,CONVERT(VARCHAR(3),NR_SKILL)	AS NR_SKILL
    ,NM_SKILL_NOME
    ,NM_PILAR_NOME
    ,NM_OPERACAO_NOME
    ,NM_CELULA_NOME
    ,NM_SEGMENTO_NOME
    ,NM_PROGRAMA_NOME
    ,NR_HORARIO
    ,NR_CHAMS_PERMS
    ,NR_CHAMS_ATEND
    ,VL_NIVEL_AT
    ,VL_FCL09_AT
    ,VL_TMO_CMS
    ,VL_TMO_SEG
    ,VL_TME_CMS
    ,VL_TME_SEG
    ,NR_ATEND_0_A_A2
    ,NR_ATEND_A2_A_A3
    ,NR_ATEND_A3_A_A5
    ,NR_ATEND_MAIOR_A5
    ,NR_ABAN_0_A_A2
    ,NR_ABAN_MAIOR_A5
    ,NR_CHAMS_ABAND
    ,NR_TEMPO_DAC_SEG
    ,NR_TEMPO_POS_AT_SEG
    ,NR_TEMPO_TOCANDO_SEG
    ,NR_TEMPO_HOLD_SEG
    ,NR_TRANS_EXT
    ,NR_ATEND_MAIOR_A6
    ,NR_ABAN_MAIOR_A6
    ,NR_TOTAL_ATEND_ATE_A1
    ,NR_TOTAL_ATEND_ATE_A2
    ,NR_TOTAL_ATEND_ATE_A3
    ,NR_TOTAL_ATEND_ATE_A4
    ,NR_TOTAL_ATEND_ATE_A5
    ,NR_TOTAL_ATEND_ATE_A6
    ,NR_TOTAL_ABAND_ATE_A1
    ,NR_TOTAL_ABAND_ATE_A2
    ,NR_TOTAL_ABAND_ATE_A3
    ,NR_TOTAL_ABAND_ATE_A4
    ,NR_TOTAL_ABAND_ATE_A5
    ,NR_TOTAL_ABAND_ATE_A6
    ,NR_CHAM_FORA_DA_CENTRAL
    ,VL_TEMPO_MEDIO_FORA_DA_CENTRAL_SEG
    ,NR_TEMPO_DAC_FORA_DA_CENTRAL_SEG
    ,NR_CHAMS_RAMAL_SAIDA
    ,VL_TEMPO_MEDIO_RAMAL_SAIDA_SEG
    ,NR_TEMPO_RAMAL_SAIDA_SEG
    ,NR_ANSTIME_SEG
    ,NR_CHAMS_OCUP_FORCADO
    ,NR_CHAMS_RVDAS_FILAS
    ,NR_CHAMS_DESC_FORCADA
    ,NR_FLUXO_SAIDA
    ,NR_CHAM_CONF
    ,NR_CHAM_ATEND_ACEITAVEL
    ,NR_CHAM_ABAND_ACEITAVEL
    ,NR_TEMPO_MAXIMO_DE_ESPERA
    ,VL_TEMPO_MED_ABAN_SEG
FROM 
	DB_SAMSUNG.DBO.TB_SAMS_CMS_DESEMP_SERV_INTERV_GR_DIV_MIS_01
WHERE 
	NM_CELULA_NOME = 'INSS HOTLINE'

UNION

SELECT 
	DT_DATA
	,LEFT(@SKILLS,LEN(@SKILLS)-1)				AS NR_SKILL
    ,CMS.NM_SKILL_NOME
    ,CMS.NM_PILAR_NOME
    ,CMS.NM_OPERACAO_NOME
    ,CMS.NM_CELULA_NOME
    ,CMS.NM_SEGMENTO_NOME
    ,CMS.NM_PROGRAMA_NOME
    ,CMS.NR_HORARIO
    ,SUM(CMS.NR_CHAMS_PERMS)					AS NR_CHAMS_PERMS
    ,SUM(CMS.NR_CHAMS_ATEND)					AS NR_CHAMS_ATEND
    ,SUM(CMS.VL_NIVEL_AT)						AS VL_NIVEL_AT
    ,SUM(CMS.VL_FCL09_AT)						AS VL_FCL09_AT
    ,SUM(CMS.VL_TMO_CMS)						AS VL_TMO_CMS
    ,SUM(CMS.VL_TMO_SEG)						AS VL_TMO_SEG
    ,SUM(CMS.VL_TME_CMS)						AS VL_TME_CMS
    ,SUM(CMS.VL_TME_SEG)						AS VL_TME_SEG
    ,SUM(CMS.NR_ATEND_0_A_A2)					AS NR_ATEND_0_A_A2
    ,SUM(CMS.NR_ATEND_A2_A_A3)					AS NR_ATEND_A2_A_A3
    ,SUM(CMS.NR_ATEND_A3_A_A5)					AS NR_ATEND_A3_A_A5
    ,SUM(CMS.NR_ATEND_MAIOR_A5)					AS NR_ATEND_MAIOR_A5
    ,SUM(CMS.NR_ABAN_0_A_A2)					AS NR_ABAN_0_A_A2
    ,SUM(CMS.NR_ABAN_MAIOR_A5)					AS NR_ABAN_MAIOR_A5
    ,SUM(CMS.NR_CHAMS_ABAND)					AS NR_CHAMS_ABAND
    ,SUM(CMS.NR_TEMPO_DAC_SEG)					AS NR_TEMPO_DAC_SEG
    ,SUM(CMS.NR_TEMPO_POS_AT_SEG)				AS NR_TEMPO_POS_AT_SEG
    ,SUM(CMS.NR_TEMPO_TOCANDO_SEG)				AS NR_TEMPO_TOCANDO_SEG
    ,SUM(CMS.NR_TEMPO_HOLD_SEG)					AS NR_TEMPO_HOLD_SEG
    ,SUM(CMS.NR_TRANS_EXT)						AS NR_TRANS_EXT
    ,SUM(CMS.NR_ATEND_MAIOR_A6)					AS NR_ATEND_MAIOR_A6
    ,SUM(CMS.NR_ABAN_MAIOR_A6)					AS NR_ABAN_MAIOR_A6
    ,SUM(CMS.NR_TOTAL_ATEND_ATE_A1)				AS NR_TOTAL_ATEND_ATE_A1
    ,SUM(CMS.NR_TOTAL_ATEND_ATE_A2)				AS NR_TOTAL_ATEND_ATE_A2
    ,SUM(CMS.NR_TOTAL_ATEND_ATE_A3)				AS NR_TOTAL_ATEND_ATE_A3
    ,SUM(CMS.NR_TOTAL_ATEND_ATE_A4)				AS NR_TOTAL_ATEND_ATE_A4
    ,SUM(CMS.NR_TOTAL_ATEND_ATE_A5)				AS NR_TOTAL_ATEND_ATE_A5
    ,SUM(CMS.NR_TOTAL_ATEND_ATE_A6)				AS NR_TOTAL_ATEND_ATE_A6
    ,SUM(CMS.NR_TOTAL_ABAND_ATE_A1)				AS NR_TOTAL_ABAND_ATE_A1
    ,SUM(CMS.NR_TOTAL_ABAND_ATE_A2)				AS NR_TOTAL_ABAND_ATE_A2
    ,SUM(CMS.NR_TOTAL_ABAND_ATE_A3)				AS NR_TOTAL_ABAND_ATE_A3
    ,SUM(CMS.NR_TOTAL_ABAND_ATE_A4)				AS NR_TOTAL_ABAND_ATE_A4
    ,SUM(CMS.NR_TOTAL_ABAND_ATE_A5)				AS NR_TOTAL_ABAND_ATE_A5
    ,SUM(CMS.NR_TOTAL_ABAND_ATE_A6)				AS NR_TOTAL_ABAND_ATE_A6
    ,SUM(CMS.NR_CHAM_FORA_DA_CENTRAL)			AS NR_CHAM_FORA_DA_CENTRAL
    ,SUM(CMS.VL_TEMPO_MEDIO_FORA_DA_CENTRAL_SEG)AS VL_TEMPO_MEDIO_FORA_DA_CENTRAL_SEG	
    ,SUM(CMS.NR_TEMPO_DAC_FORA_DA_CENTRAL_SEG)	AS NR_TEMPO_DAC_FORA_DA_CENTRAL_SEG
    ,SUM(CMS.NR_CHAMS_RAMAL_SAIDA)				AS NR_CHAMS_RAMAL_SAIDA
    ,SUM(CMS.VL_TEMPO_MEDIO_RAMAL_SAIDA_SEG)	AS VL_TEMPO_MEDIO_RAMAL_SAIDA_SEG
    ,SUM(CMS.NR_TEMPO_RAMAL_SAIDA_SEG)			AS NR_TEMPO_RAMAL_SAIDA_SEG
    ,SUM(CMS.NR_ANSTIME_SEG)					AS NR_ANSTIME_SEG
    ,SUM(CMS.NR_CHAMS_OCUP_FORCADO)				AS NR_CHAMS_OCUP_FORCADO
    ,SUM(CMS.NR_CHAMS_RVDAS_FILAS)				AS NR_CHAMS_RVDAS_FILAS
    ,SUM(CMS.NR_CHAMS_DESC_FORCADA)				AS NR_CHAMS_DESC_FORCADA
    ,SUM(CMS.NR_FLUXO_SAIDA)					AS NR_FLUXO_SAIDA
    ,SUM(CMS.NR_CHAM_CONF)						AS NR_CHAM_CONF
    ,SUM(CMS.NR_CHAM_ATEND_ACEITAVEL)			AS NR_CHAM_ATEND_ACEITAVEL
    ,SUM(CMS.NR_CHAM_ABAND_ACEITAVEL)			AS NR_CHAM_ABAND_ACEITAVEL
    ,SUM(CMS.NR_TEMPO_MAXIMO_DE_ESPERA)			AS NR_TEMPO_MAXIMO_DE_ESPERA
    ,SUM(CMS.VL_TEMPO_MED_ABAN_SEG)				AS VL_TEMPO_MED_ABAN_SEG
 FROM 
	DB_SAMSUNG.DBO.TB_SAMS_CMS_DESEMP_SERV_INTERV_GR_DIV_MIS_01 AS CMS
 WHERE 
	NM_CELULA_NOME = 'INSS HOTLINE'
 GROUP BY
	 DT_DATA
	,NR_SKILL
	,NM_SKILL_NOME
	,NM_PILAR_NOME
	,NM_OPERACAO_NOME
	,NM_CELULA_NOME
	,NM_SEGMENTO_NOME
	,NM_PROGRAMA_NOME
	,NR_HORARIO