-- CONSULTOR  -- consuta 1 --- nome: base Analitica
USE DB_OUTROS
SELECT [TICKET]
      ,[PROCESS TYPE]
      ,[STATUS DESC]
      ,[REASON DESCRIPTION]
      ,[COMMENTS]
      ,[POSTING DATE]
      ,[CHANNEL DESC]
      ,[CATEGORY1 DESCRIPTION]
      ,[CATEGORY2 DESCRIPTION]
      ,[CATEGORY3 DESCRIPTION]
      ,[CREATED BY]
      ,LTRIM(REPLACE(IIF(Q.[SUPERVISOR] IS NULL,'-','ATENTO'),'  ',' ')) AS [EMPRESA]
      ,LTRIM(REPLACE(IIF(Q.[GRUPO] IS NULL,'-',Q.[GRUPO]),'  ',' ')) AS [GRUPO]
      ,LTRIM(REPLACE(IIF(Q.[AGENTE] IS NULL,'-',Q.[AGENTE]),'  ',' ')) AS [AGENTE]
      ,LTRIM(REPLACE(IIF(Q.[SUPERVISOR] IS NULL,'-',Q.[SUPERVISOR]),'  ',' ')) AS [SUPERVISOR]
         --,S.[CATEGORIA]
FROM [DBO].[TB_SAMS_SAP_ATR_GATA] A WITH (NOLOCK)
LEFT JOIN (SELECT DISTINCT [DATA], [SAP GCIC], RE, SUPERVISOR, AGENTE, GRUPO FROM DB_OUTROS..TB_SAMS_MANUAL_QUADRO WITH (NOLOCK)
WHERE CONVERT(DATETIME,[DATA],103) = (SELECT MAX(CONVERT(DATETIME,[DATA],103)) FROM DB_OUTROS..TB_SAMS_MANUAL_QUADRO)) Q
ON Q.[SAP GCIC] = A.[CREATED BY]
LEFT JOIN DB_DEPARA..TB_SAMS_DP_SKILL S WITH (NOLOCK)
ON S.TIPO = A.[CATEGORY ID]
WHERE 

YEAR (CONVERT(DATE,[POSTING DATE],103)) >= 2019
AND ([PROCESS TYPE] LIKE 'TECHNICAL ADVICE%' OR [PROCESS TYPE] LIKE 'GENERAL ADVICE%')
AND ([GRUPO] LIKE '%CONSULTOR TÉCNICO LINHA BRANCA%' OR [GRUPO] LIKE '%CONSULTOR TÉCNICO TECH TV%')


ORDER BY 6