--Validação -- consulta 2 --- nome: analitica_validacao

DECLARE @DATAINI AS DATE, @DATAFIM AS DATE
SET @DATAINI = '2019-01-01'
SET @DATAFIM = CONVERT(date, getdate()-1,103)

SELECT 

	[TICKET]
	,[PROCESS TYPE]
	,[STATUS DESC]
	,[REASON DESCRIPTION]
	,[COMMENTS]
	,convert(date, [POSTING DATE], 103) as [POSTING DATE]
	,[CHANNEL DESC]
	,[CATEGORY1 DESCRIPTION]
	,[CATEGORY2 DESCRIPTION]
	,[CATEGORY3 DESCRIPTION]
	,[CREATED BY]
	,LTRIM(REPLACE(IIF(Q.[SUPERVISOR] IS NULL,'-','ATENTO'),'  ',' ')) AS [EMPRESA]
	,CASE WHEN Q.[GRUPO] IN ('WSM', 'REF_ACN') THEN  'LINHA BRANCA'
		WHEN Q.[GRUPO] IN ('NOTEPC') THEN 'NOTE PC'
		ELSE Q.[GRUPO] END AS [GRUPO]
	,Q.[AGENTE] AS [AGENTE]
	,Q.[SUPERVISOR]  AS [SUPERVISOR]
	,ROW_NUMBER() OVER(PARTITION BY [TICKET] ORDER BY Q.[GRUPO], Q.[AGENTE] ASC) AS 'Duplicados'
FROM [DB_OUTROS].[DBO].[TB_SAMS_SAP_ATR_GATA] A WITH (NOLOCK)
LEFT JOIN (SELECT DISTINCT [DATA], [SAP GCIC], RE, SUPERVISOR, AGENTE, GRUPO FROM DB_OUTROS..TB_SAMS_MANUAL_QUADRO WITH (NOLOCK)) Q
ON Q.[SAP GCIC] = A.[CREATED BY] and CONVERT(DATETIME,Q.[DATA],103) = CONVERT(DATE, a.[POSTING DATE], 103)
WHERE 
	([PROCESS TYPE] LIKE 'TECHNICAL ADVICE%')
	AND CONVERT(DATE, [POSTING DATE], 103) BETWEEN @DATAINI AND @DATAFIM
	AND Q.GRUPO IN ('LINHA BRANCA', 'REF_ACN', 'TECH TV', 'WSM')
	AND [REASON DESCRIPTION] LIKE 'Transfer to Service Request%'