	> criar duas colunas novas no lugar dessa (acordo completed_soluction e acordo agreed_soluction)
	 e retornar sim ou nao

	> fazer join com a tabela de_para ([DB_DEPARA].[dbo].[TB_SAMS_DP_SOLUTIONS])

------------------------------------------------------------------------------------------------------------

SELECT
	CASE 
		WHEN REP.NM_CLAIM_TYPE_DESC_1 LIKE 'COURT%' THEN 'COURT' 
		ELSE '-' 
	END									AS NM_COMPARATIVO_COURT
	,CASE 
		WHEN REP.NM_CLAIM_TYPE_DESC_1 LIKE 'COURT%' THEN REP.NM_TICKET_NO
		ELSE '-' 
	END									AS NM_TRANSACTION_COURT								
	,CASE 
		WHEN REP.NM_CLAIM_TYPE_DESC_1 = 'Procon (AUD)' THEN 'AUD' 
		ELSE '-' 
	END									AS NM_COMPARATIVO_AUD
	,CASE 
		WHEN REP.NM_CLAIM_TYPE_DESC_1 = 'Procon (AUD)' THEN REP.NM_TICKET_NO
		ELSE '-' 
	END									AS NM_TRANSACTION_AUD		
	,CASE 
		WHEN REP.NM_CLAIM_TYPE_DESC_1 = 'Procon (CIP)' THEN 'CIP' 
		ELSE '-' 
	END									AS NM_COMPARATIVO_CIP
	,CASE 
		WHEN REP.NM_CLAIM_TYPE_DESC_1 = 'Procon (CIP)' THEN REP.NM_TICKET_NO
		ELSE '-' 
	END									AS NM_TRANSACTION_CIP	
	,ISNULL(DATEDIFF(DAY, VOC.DT_POSTING_DATE,VOC.DT_COMPLETE_DATE),'-') AS NR_TAT_FINALIZACAO
	,COMP.NM_ACORDO	AS NM_COMPLETED_SOLUCTION
	,AGRE.NM_ACORDO	AS NM_AGREED_SOLUTION
	,VOC.NM_TRANSACTION_ID
	,VOC.DT_POSTING_DATE
	,VOC.DT_COMPLETE_DATE
	,VOC.NR_STATUS
	,VOC.NM_REASON_T
	,VOC.NM_PRODUCT_CATEGORY
	,VOC.NM_MODEL
	,VOC.NM_CLAIM_TYPE_I
	,VOC.NM_CLAIM_TYPE_II
	,VOC.NM_COMPLETED_SOLUTION_I
	,VOC.NM_COMPLETED_SOLUTION_II
	,VOC.NM_ROOT_CAUSE
	,VOC.NM_ASC_CODE_1
	,VOC.NM_TYPE
	,VOC.NM_CITY
	,VOC.NM_STATE
	,VOC.NM_COURT_NAME
	,VOC.NM_COURT_CITY
	,VOC.NM_SYMPTOM_1
	,VOC.NM_SYMPTOM_2
	,VOC.NM_SYMPTOM_3
	,VOC.NM_SERVICE_TYPE_T
	,VOC.NM_REQUIREMENT_T
	,VOC.NM_SOURCE_CHANNEL_T
	,VOC.NM_STATUS_REASON
FROM DB_SAMSUNG.dbo.DB_SAMSUNG.DBO.TB_SAMS_VOCS		AS VOC
LEFT JOIN DB_SAMSUNG.dbo.TB_SAMS_VOCS_REPORT		AS REP 
	ON VOC.NM_TRANSACTION_ID = REP.NM_REF_TICKET
LEFT JOIN DB_SAMSUNG.dbo.TB_DIM_SAMS_VOCS_SOLUTIONS AS COMP
	ON VOC.NM_COMPLETED_SOLUTION_I = COMP.NR_ID_SOLUTION
LEFT JOIN DB_SAMSUNG.dbo.TB_DIM_SAMS_VOCS_SOLUTIONS AS AGRE
	ON VOC.NM_AGREED_SOLUTION_I = AGRE.NR_ID_SOLUTION





	