CREATE PROCEDURE  dbo.PRC_SAMS_CARGA_VOCS AS 

BEGIN

DELETE FROM DB_SAMSUNG.DBO.TB_SAMS_VOCS WHERE NM_TRANSACTION_ID IN (SELECT LEFT(NM_TRANSACTION_ID,LEN(NM_TRANSACTION_ID)-1) FROM DB_SAMSUNG.DBO.TB_STG_SAMS_VOCS)

INSERT INTO DB_SAMSUNG.DBO.TB_SAMS_VOCS
(
	NM_TRANSACTION_ID
	,NM_COMPANY
	,NM_COUNTRY
	,NM_POSTING_DATE
	,NM_STATUS
	,NM_STATUS_T_1
	,NM_SUB_STATUS
	,NM_SUB_STATUS_T
	,NM_STATUS_REASON
	,NM_CLAIM_DELAY_REASON
	,NM_CLAIM_DELAY_REASON_T
	,NM_PRIORITY
	,NM_PRIORITY_T
	,NM_CALL_CUSTOMER
	,NM_CALL_CUSTOMER_T
	,NM_CONTACT_PERSON
	,NM_CONTACT_PERSON_T
	,NM_END_CUSTOMER
	,NM_END_CUSTOMER_T
	,NM_END_CUSTOMER_CONTACT_PERSON
	,NM_END_CUSTOMER_CONTACT_PERSON_T
	,NM_CUSTOMER_INFO_FOR
	,NM_CUSTOMER_FIRST_NAME
	,NM_CUSTOMER_LAST_NAME
	,NM_CUSTOMER_PHONE_H
	,NM_CUSTOMER_PHONE_M
	,NM_STREET_1
	,NM_STREET_2
	,NM_CITY
	,NM_STATE
	,NM_STATE_T
	,NM_CITY_POSTAL_CODE
	,NM_COUNTRY_KEY
	,NM_COUNTRY_KEY_T
	,NM_E_MAIL_ADDRESS
	,NM_RECIPIENT
	,NM_RECIPIENT_T
	,NM_RECIPIENT_GROUP
	,NM_RECIPIENT_GROUP_T
	,NM_EMPLOYEE_RESPONSIBLE
	,NM_EMPLOYEE_RESPONSIBLE_T
	,NM_EMPLOYEE_GROUP
	,NM_EMPLOYEE_GROUP_T
	,NM_OCCURRENCE_DATE
	,NM_REQUIREMENT
	,NM_REQUIREMENT_T
	,NM_TYPE
	,NM_TYPE_T
	,NM_CLAIM_TYPE_I
	,NM_CLAIM_TYPE_I_T
	,NM_CLAIM_TYPE_II
	,NM_CLAIM_TYPE_II_T
	,NM_CLAIM_TYPE_III
	,NM_CLAIM_TYPE_III_T
	,NM_AGREED_SOLUTION_I
	,NM_AGREED_SOLUTION_I_T
	,NM_AGREED_SOLUTION_II
	,NM_AGREED_SOLUTION_II_T
	,NM_AGREED_DATE
	,NM_AGREED_TIME
	,NM_AGREED_TAT
	,NM_COMPLETED_SOLUTION_I
	,NM_COMPLETED_SOLUTION_I_T
	,NM_COMPLETED_SOLUTION_II
	,NM_COMPLETED_SOLUTION_II_T
	,NM_COMPLETED_TAT
	,NM_COMPLETE_DATE
	,NM_COMPLETE_TIME
	,NM_CUSTOMERS_COMMENTS_HISTORY
	,NM_INCURRED_AMOUNT
	,NM_CURRENCY_1
	,NM_CALLBACK_DATE
	,NM_CALLBACK_TIME_ZONE
	,NM_CALLBACK_TELEPHONE
	,NM_CALLBACK_E_MAIL
	,NM_PRODUCT_MAJOR_CATEGORY
	,NM_PRODUCT_CATEGORY
	,NM_PRODUCT_SUB_CATEGORY
	,NM_G_ERP_SERVICE_PRODUCT_CODE
	,NM_LOCAL_SERVCIE_PRODUCT_CODE
	,NM_MODEL
	,NM_SERIAL
	,NM_ESN_IMEI
	,NM_PURCHASED_DATE
	,NM_PRODUCTION_DATE
	,NM_PLACE_OF_PURCHASE
	,NM_WTY_I_O
	,NM_CONTRACT_NO
	,NM_REF_SERVICE
	,NM_SOURCE_CHANNEL
	,NM_SOURCE_CHANNEL_T
	,NM_SUBJECT
	,NM_PROCESS_TYPE
	,NM_PROCESS_TYPE_T
	,NM_ASC_CODE_1
	,NM_ASC_NAME_1
	,NM_CHANGED_AT_1
	,NM_CHANGED_BY_1
	,NM_CHANGED_BY_T
	,NM_CASE_NO
	,NM_REFERENCE_NO
	,NM_BRANCH
	,NM_CASE_SUB_TYPE
	,NM_CASE_SUB_TYPE_T
	,NM_REGION
	,NM_DISTRIBUTED_DATE
	,NM_COURT_NAME
	,NM_COURT_CITY
	,NM_NOTIFICATION_DATE
	,NM_NOTIFICATION_PLACE
	,NM_NOTIFICATION_PLACE_T
	,NM_DEFENDANT
	,NM_LAWYER_NAME
	,NM_LICENSE_NO
	,NM_CASE_TITLE
	,NM_CASE_RESPONSIBILTY
	,NM_CASE_RESPONSIBILTY_T
	,NM_CASE_VALUE
	,NM_MATERIAL_DAMAGE
	,NM_MORAL_DAMAGE
	,NM_NOTIFICATION_RECEIVED
	,NM_NOTIFICATION_RECEIVED_T
	,NM_INVOICE_VALUE
	,NM_LITIGATION_COST
	,NM_COMPENSATION_AMOUNT_1
	,NM_CASE_STATUS
	,NM_CASE_STATUS_T
	,NM_MEDIATION_FAILURE
	,NM_MEDIATION_FAILURE_T
	,NM_WAITING_REASON
	,NM_WAITING_REASON_T
	,NM_FULFILLMENT_RESOLUTION
	,NM_FULFILLMENT_RESOLUTION_T
	,NM_ADDITIONAL_RESOLUTION
	,NM_ADDITIONAL_RESOLUTION_T
	,NM_COMPLETE_TYPE
	,NM_COMPLETE_TYPE_T
	,NM_COMPLETE_TEXT
	,NM_FINAL_VALUE
	,NM_FINAL_MATERIAL_DAMAGE
	,NM_FINAL_MORAL_DAMAGE
	,NM_MEDIATION_JUDGEMENT_TEXT
	,NM_FINAL_LITIGATION_COST
	,NM_FINAL_COMPENSATION_AMOUNT
	,NM_LOS
	,NM_COPY_OF_CHEQUE
	,NM_WITHDRAWAL_ORDER
	,NM_SETTLEMENT_LETTER
	,NM_CLOSURE_ORDER
	,NM_AGREED_FULFILLMENT_DATE
	,NM_REPRESENTATIVE
	,NM_LAWYER_COST
	,NM_DEPOSIT_DATE
	,NM_DEPOSIT_AMOUNT
	,NM_PAYMENT_TYPE
	,NM_PAYMENT_TYPE_T
	,NM_REIMBURSE
	,NM_REIMBURSE_TYPE
	,NM_REIMBURSE_TYPE_T
	,NM_CURRENCY_2
	,NM_PRIORITY_REASON
	,NM_PRIORITY_REASON_T
	,NM_AGREED_ETD_DATE
	,NM_DEPT_INCHARGE
	,NM_DEPT_INCHARGE_T
	,NM_ROOT_CAUSE
	,NM_ROOT_CAUSE_T
	,NM_TRUE_STATUS
	,NM_TRUE_STATUS_T
	,NM_TRUE_REASON
	,NM_TRUE_REASON_T
	,NM_ENGINEER
	,NM_ENGINEER_T_1
	,NM_CUSTOMER_PERSPECTIVE
	,NM_CUSTOMER_PERSPECTIVE_T
	,NM_CUSTOMER_SIDE
	,NM_SAMSUNG_SIDE
	,NM_CUSTOMER_DATE
	,NM_SAMSUNG_DATE
	,NM_SERVICE_ORDER_NO
	,NM_CONTACT
	,NM_REDO_SERVICE_ORDER
	,NM_CREATED_BY
	,NM_CREATED_AT
	,NM_ASC_CODE_2
	,NM_ASC_NAME_2
	,NM_CHANGED_BY_2
	,NM_CHANGED_AT_2
	,NM_SYMPTOM_1
	,NM_SYMPTOM_2
	,NM_SYMPTOM_3
	,NM_DETAIL_TYPE_T
	,NM_SERVICE_TYPE_T
	,NM_SUB_SERVICE_TYPE_T
	,NM_SERVICE_CHANNEL
	,NM_STATUS_T_2
	,NM_REASON_T
	,NM_COMMENT
	,NM_ENGINGEER
	,NM_ENGINEER_T_2
	,NM_ASC_ENGINEER
	,NM_ENGINEER_ASSIGN_DATE
	,NM_REPAIR_COMPLETE_DATE
	,NM_RMA_NO
	,NM_RETURN_ORDER_DATE
	,NM_WARRANTY_TERM
	,NM_WARRANTY_EXCEPTION
	,NM_EX_REFUND_REASON
	,NM_SUB_REASON
	,NM_DELIVERY_TYPE_T
	,NM_CURRENCY_3
	,NM_REFUND_AMOUNT
	,NM_COMPENSATION_AMOUNT_2
	,NM_EXCHANGE_FEE
	,NM_ESTIMATED_REPAIR_COST
)
SELECT
	 LEFT(NM_TRANSACTION_ID,LEN(NM_TRANSACTION_ID)-1)										AS NM_TRANSACTION_ID
	,LEFT(NM_COMPANY,LEN(NM_COMPANY)-1)														AS NM_COMPANY
	,LEFT(NM_COUNTRY,LEN(NM_COUNTRY)-1)														AS NM_COUNTRY
	,TRY_CONVERT(DATE,NM_POSTING_DATE,103)													AS NM_POSTING_DATE
	,CONVERT(INT,LEFT(NM_STATUS,LEN(NM_STATUS)-1))											AS NM_STATUS
	,LEFT(NM_STATUS_T_1,LEN(NM_STATUS_T_1)-1)												AS NM_STATUS_T_1
	,LEFT(NM_SUB_STATUS,LEN(NM_SUB_STATUS)-1)												AS NM_SUB_STATUS
	,LEFT(NM_SUB_STATUS_T,LEN(NM_SUB_STATUS_T)-1)											AS NM_SUB_STATUS_T
	,LEFT(NM_STATUS_REASON,LEN(NM_STATUS_REASON)-1)											AS NM_STATUS_REASON
	,LEFT(NM_CLAIM_DELAY_REASON,LEN(NM_CLAIM_DELAY_REASON)-1)								AS NM_CLAIM_DELAY_REASON
	,LEFT(NM_CLAIM_DELAY_REASON_T,LEN(NM_CLAIM_DELAY_REASON_T)-1)							AS NM_CLAIM_DELAY_REASON_T
	,CONVERT(INT,LEFT(NM_PRIORITY,LEN(NM_PRIORITY)-1))										AS NM_PRIORITY
	,LEFT(NM_PRIORITY_T,LEN(NM_PRIORITY_T)-1)												AS NM_PRIORITY_T
	,LEFT(NM_CALL_CUSTOMER,LEN(NM_CALL_CUSTOMER)-1)											AS NM_CALL_CUSTOMER
	,LEFT(NM_CALL_CUSTOMER_T,LEN(NM_CALL_CUSTOMER_T)-1)										AS NM_CALL_CUSTOMER_T
	,LEFT(NM_CONTACT_PERSON,LEN(NM_CONTACT_PERSON)-1)										AS NM_CONTACT_PERSON
	,LEFT(NM_CONTACT_PERSON_T,LEN(NM_CONTACT_PERSON_T)-1)									AS NM_CONTACT_PERSON_T
	,LEFT(NM_END_CUSTOMER,LEN(NM_END_CUSTOMER)-1)											AS NM_END_CUSTOMER
	,LEFT(NM_END_CUSTOMER_T,LEN(NM_END_CUSTOMER_T)-1)										AS NM_END_CUSTOMER_T
	,LEFT(NM_END_CUSTOMER_CONTACT_PERSON,LEN(NM_END_CUSTOMER_CONTACT_PERSON)-1)				AS NM_END_CUSTOMER_CONTACT_PERSON
	,LEFT(NM_END_CUSTOMER_CONTACT_PERSON_T,LEN(NM_END_CUSTOMER_CONTACT_PERSON_T)-1)			AS NM_END_CUSTOMER_CONTACT_PERSON_T
	,LEFT(NM_CUSTOMER_INFO_FOR,LEN(NM_CUSTOMER_INFO_FOR)-1)									AS NM_CUSTOMER_INFO_FOR
	,LEFT(NM_CUSTOMER_FIRST_NAME,LEN(NM_CUSTOMER_FIRST_NAME)-1)								AS NM_CUSTOMER_FIRST_NAME
	,LEFT(NM_CUSTOMER_LAST_NAME,LEN(NM_CUSTOMER_LAST_NAME)-1)								AS NM_CUSTOMER_LAST_NAME
	,LEFT(NM_CUSTOMER_PHONE_H,LEN(NM_CUSTOMER_PHONE_H)-1)									AS NM_CUSTOMER_PHONE_H
	,LEFT(NM_CUSTOMER_PHONE_M,LEN(NM_CUSTOMER_PHONE_M)-1)									AS NM_CUSTOMER_PHONE_M
	,LEFT(NM_STREET_1,LEN(NM_STREET_1)-1)													AS NM_STREET_1
	,LEFT(NM_STREET_2,LEN(NM_STREET_2)-1)													AS NM_STREET_2
	,LEFT(NM_CITY,LEN(NM_CITY)-1)															AS NM_CITY
	,LEFT(NM_STATE,LEN(NM_STATE)-1)															AS NM_STATE
	,LEFT(NM_STATE_T,LEN(NM_STATE_T)-1)														AS NM_STATE_T
	,LEFT(NM_CITY_POSTAL_CODE,LEN(NM_CITY_POSTAL_CODE)-1)									AS NM_CITY_POSTAL_CODE
	,LEFT(NM_COUNTRY_KEY,LEN(NM_COUNTRY_KEY)-1)												AS NM_COUNTRY_KEY
	,LEFT(NM_COUNTRY_KEY_T,LEN(NM_COUNTRY_KEY_T)-1)											AS NM_COUNTRY_KEY_T
	,LEFT(NM_E_MAIL_ADDRESS,LEN(NM_E_MAIL_ADDRESS)-1)										AS NM_E_MAIL_ADDRESS
	,LEFT(NM_RECIPIENT,LEN(NM_RECIPIENT)-1)													AS NM_RECIPIENT
	,LEFT(NM_RECIPIENT_T,LEN(NM_RECIPIENT_T)-1)												AS NM_RECIPIENT_T
	,LEFT(NM_RECIPIENT_GROUP,LEN(NM_RECIPIENT_GROUP)-1)										AS NM_RECIPIENT_GROUP
	,LEFT(NM_RECIPIENT_GROUP_T,LEN(NM_RECIPIENT_GROUP_T)-1)									AS NM_RECIPIENT_GROUP_T
	,LEFT(NM_EMPLOYEE_RESPONSIBLE,LEN(NM_EMPLOYEE_RESPONSIBLE)-1)							AS NM_EMPLOYEE_RESPONSIBLE
	,LEFT(NM_EMPLOYEE_RESPONSIBLE_T,LEN(NM_EMPLOYEE_RESPONSIBLE_T)-1)						AS NM_EMPLOYEE_RESPONSIBLE_T
	,LEFT(NM_EMPLOYEE_GROUP,LEN(NM_EMPLOYEE_GROUP)-1)										AS NM_EMPLOYEE_GROUP
	,LEFT(NM_EMPLOYEE_GROUP_T,LEN(NM_EMPLOYEE_GROUP_T)-1)									AS NM_EMPLOYEE_GROUP_T
	,TRY_CONVERT(DATE,NM_OCCURRENCE_DATE,103)												AS NM_OCCURRENCE_DATE
	,LEFT(NM_REQUIREMENT,LEN(NM_REQUIREMENT)-1)												AS NM_REQUIREMENT
	,LEFT(NM_REQUIREMENT_T,LEN(NM_REQUIREMENT_T)-1)											AS NM_REQUIREMENT_T
	,LEFT(NM_TYPE,LEN(NM_TYPE)-1)															AS NM_TYPE
	,LEFT(NM_TYPE_T,LEN(NM_TYPE_T)-1)														AS NM_TYPE_T
	,LEFT(NM_CLAIM_TYPE_I,LEN(NM_CLAIM_TYPE_I)-1)											AS NM_CLAIM_TYPE_I
	,LEFT(NM_CLAIM_TYPE_I_T,LEN(NM_CLAIM_TYPE_I_T)-1)										AS NM_CLAIM_TYPE_I_T
	,LEFT(NM_CLAIM_TYPE_II,LEN(NM_CLAIM_TYPE_II)-1)											AS NM_CLAIM_TYPE_II
	,LEFT(NM_CLAIM_TYPE_II_T,LEN(NM_CLAIM_TYPE_II_T)-1)										AS NM_CLAIM_TYPE_II_T
	,LEFT(NM_CLAIM_TYPE_III,LEN(NM_CLAIM_TYPE_III)-1)										AS NM_CLAIM_TYPE_III
	,LEFT(NM_CLAIM_TYPE_III_T,LEN(NM_CLAIM_TYPE_III_T)-1)									AS NM_CLAIM_TYPE_III_T
	,LEFT(NM_AGREED_SOLUTION_I,LEN(NM_AGREED_SOLUTION_I)-1)									AS NM_AGREED_SOLUTION_I
	,LEFT(NM_AGREED_SOLUTION_I_T,LEN(NM_AGREED_SOLUTION_I_T)-1)								AS NM_AGREED_SOLUTION_I_T
	,LEFT(NM_AGREED_SOLUTION_II,LEN(NM_AGREED_SOLUTION_II)-1)								AS NM_AGREED_SOLUTION_II
	,LEFT(NM_AGREED_SOLUTION_II_T,LEN(NM_AGREED_SOLUTION_II_T)-1)							AS NM_AGREED_SOLUTION_II_T
	,TRY_CONVERT(DATE,NM_AGREED_DATE,103)													AS NM_AGREED_DATE
	,LEFT(NM_AGREED_TIME,LEN(NM_AGREED_TIME)-1)												AS NM_AGREED_TIME
	,LEFT(NM_AGREED_TAT,LEN(NM_AGREED_TAT)-1)												AS NM_AGREED_TAT
	,LEFT(NM_COMPLETED_SOLUTION_I,LEN(NM_COMPLETED_SOLUTION_I)-1)							AS NM_COMPLETED_SOLUTION_I
	,LEFT(NM_COMPLETED_SOLUTION_I_T,LEN(NM_COMPLETED_SOLUTION_I_T)-1)						AS NM_COMPLETED_SOLUTION_I_T
	,LEFT(NM_COMPLETED_SOLUTION_II,LEN(NM_COMPLETED_SOLUTION_II)-1)							AS NM_COMPLETED_SOLUTION_II
	,LEFT(NM_COMPLETED_SOLUTION_II_T,LEN(NM_COMPLETED_SOLUTION_II_T)-1)						AS NM_COMPLETED_SOLUTION_II_T
	,LEFT(NM_COMPLETED_TAT,LEN(NM_COMPLETED_TAT)-1)											AS NM_COMPLETED_TAT
	,TRY_CONVERT(DATE,NM_COMPLETE_DATE,103)													AS NM_COMPLETE_DATE
	,LEFT(NM_COMPLETE_TIME,LEN(NM_COMPLETE_TIME)-1)											AS NM_COMPLETE_TIME
	,LEFT(NM_CUSTOMERS_COMMENTS_HISTORY,LEN(NM_CUSTOMERS_COMMENTS_HISTORY)-1)				AS NM_CUSTOMERS_COMMENTS_HISTORY
	,CONVERT(FLOAT,LEFT(NM_INCURRED_AMOUNT, LEN(NM_INCURRED_AMOUNT)-2))						AS NM_INCURRED_AMOUNT
	,LEFT(NM_CURRENCY_1,LEN(NM_CURRENCY_1)-1)												AS NM_CURRENCY_1
	,CONVERT(DATETIME2(0),LEFT(NM_CALLBACK_DATE,LEN(NM_CALLBACK_DATE)-1),103)				AS NM_CALLBACK_DATE
	,LEFT(NM_CALLBACK_TIME_ZONE,LEN(NM_CALLBACK_TIME_ZONE)-1)								AS NM_CALLBACK_TIME_ZONE
	,LEFT(NM_CALLBACK_TELEPHONE,LEN(NM_CALLBACK_TELEPHONE)-1)								AS NM_CALLBACK_TELEPHONE
	,LEFT(NM_CALLBACK_E_MAIL,LEN(NM_CALLBACK_E_MAIL)-1)										AS NM_CALLBACK_E_MAIL
	,LEFT(NM_PRODUCT_MAJOR_CATEGORY,LEN(NM_PRODUCT_MAJOR_CATEGORY)-1)						AS NM_PRODUCT_MAJOR_CATEGORY
	,LEFT(NM_PRODUCT_CATEGORY,LEN(NM_PRODUCT_CATEGORY)-1)									AS NM_PRODUCT_CATEGORY
	,LEFT(NM_PRODUCT_SUB_CATEGORY,LEN(NM_PRODUCT_SUB_CATEGORY)-1)							AS NM_PRODUCT_SUB_CATEGORY
	,LEFT(NM_G_ERP_SERVICE_PRODUCT_CODE,LEN(NM_G_ERP_SERVICE_PRODUCT_CODE)-1)				AS NM_G_ERP_SERVICE_PRODUCT_CODE
	,LEFT(NM_LOCAL_SERVCIE_PRODUCT_CODE,LEN(NM_LOCAL_SERVCIE_PRODUCT_CODE)-1)				AS NM_LOCAL_SERVCIE_PRODUCT_CODE
	,LEFT(NM_MODEL,LEN(NM_MODEL)-1)															AS NM_MODEL
	,LEFT(NM_SERIAL,LEN(NM_SERIAL)-1)														AS NM_SERIAL
	,LEFT(NM_ESN_IMEI,LEN(NM_ESN_IMEI)-1)													AS NM_ESN_IMEI
	,TRY_CONVERT(DATE,NM_PURCHASED_DATE,103)												AS NM_PURCHASED_DATE
	,TRY_CONVERT(DATE,NM_PRODUCTION_DATE,103)												AS NM_PRODUCTION_DATE
	,LEFT(NM_PLACE_OF_PURCHASE,LEN(NM_PLACE_OF_PURCHASE)-1)									AS NM_PLACE_OF_PURCHASE
	,LEFT(NM_WTY_I_O,LEN(NM_WTY_I_O)-1) 													AS NM_WTY_I_O	
	,LEFT(NM_CONTRACT_NO,LEN(NM_CONTRACT_NO)-1)												AS NM_CONTRACT_NO
	,LEFT(NM_REF_SERVICE,LEN(NM_REF_SERVICE)-1)												AS NM_REF_SERVICE
	,LEFT(NM_SOURCE_CHANNEL,LEN(NM_SOURCE_CHANNEL)-1)										AS NM_SOURCE_CHANNEL
	,LEFT(NM_SOURCE_CHANNEL_T,LEN(NM_SOURCE_CHANNEL_T)-1)									AS NM_SOURCE_CHANNEL_T
	,LEFT(NM_SUBJECT,LEN(NM_SUBJECT)-1)														AS NM_SUBJECT
	,LEFT(NM_PROCESS_TYPE,LEN(NM_PROCESS_TYPE)-1)											AS NM_PROCESS_TYPE
	,LEFT(NM_PROCESS_TYPE_T,LEN(NM_PROCESS_TYPE_T)-1)										AS NM_PROCESS_TYPE_T
	,LEFT(NM_ASC_CODE_1,LEN(NM_ASC_CODE_1)-2)												AS NM_ASC_CODE_1
	,LEFT(NM_ASC_NAME_1,LEN(NM_ASC_NAME_1)-1)												AS NM_ASC_NAME_1
	,CONVERT(DATETIME2(0),LEFT(NM_CHANGED_AT_1,LEN(NM_CHANGED_AT_1)-1),103)					AS NM_CHANGED_AT_1
	,LEFT(NM_CHANGED_BY_1,LEN(NM_CHANGED_BY_1)-1)											AS NM_CHANGED_BY_1
	,LEFT(NM_CHANGED_BY_T,LEN(NM_CHANGED_BY_T)-1)											AS NM_CHANGED_BY_T
	,LEFT(NM_CASE_NO,LEN(NM_CASE_NO)-1)														AS NM_CASE_NO
	,LEFT(NM_REFERENCE_NO,LEN(NM_REFERENCE_NO)-1)											AS NM_REFERENCE_NO
	,LEFT(NM_BRANCH,LEN(NM_BRANCH)-1)														AS NM_BRANCH
	,LEFT(NM_CASE_SUB_TYPE,LEN(NM_CASE_SUB_TYPE)-1)											AS NM_CASE_SUB_TYPE
	,LEFT(NM_CASE_SUB_TYPE_T,LEN(NM_CASE_SUB_TYPE_T)-1)										AS NM_CASE_SUB_TYPE_T
	,LEFT(NM_REGION,LEN(NM_REGION)-1)														AS NM_REGION
	,TRY_CONVERT(DATE,NM_DISTRIBUTED_DATE,103)												AS NM_DISTRIBUTED_DATE
	,LEFT(NM_COURT_NAME,LEN(NM_COURT_NAME)-1)												AS NM_COURT_NAME
	,LEFT(NM_COURT_CITY,LEN(NM_COURT_CITY)-1)												AS NM_COURT_CITY
	,TRY_CONVERT(DATE,NM_NOTIFICATION_DATE,103)												AS NM_NOTIFICATION_DATE
	,LEFT(NM_NOTIFICATION_PLACE,LEN(NM_NOTIFICATION_PLACE)-1)								AS NM_NOTIFICATION_PLACE
	,LEFT(NM_NOTIFICATION_PLACE_T,LEN(NM_NOTIFICATION_PLACE_T)-1)							AS NM_NOTIFICATION_PLACE_T	
	,LEFT(NM_DEFENDANT,LEN(NM_DEFENDANT)-1)													AS NM_DEFENDANT
	,LEFT(NM_LAWYER_NAME,LEN(NM_LAWYER_NAME)-1)												AS NM_LAWYER_NAME
	,LEFT(NM_LICENSE_NO,LEN(NM_LICENSE_NO)-1)												AS NM_LICENSE_NO
	,LEFT(NM_CASE_TITLE,LEN(NM_CASE_TITLE)-1)												AS NM_CASE_TITLE
	,CONVERT(INT,LEFT(NM_CASE_RESPONSIBILTY,LEN(NM_CASE_RESPONSIBILTY)-1))					AS NM_CASE_RESPONSIBILTY
	,LEFT(NM_CASE_RESPONSIBILTY_T,LEN(NM_CASE_RESPONSIBILTY_T)-1)							AS NM_CASE_RESPONSIBILTY_T
	,CONVERT(FLOAT,LEFT(NM_CASE_VALUE, LEN(NM_CASE_VALUE)-2))								AS NM_CASE_VALUE
	,CONVERT(FLOAT,LEFT(NM_MATERIAL_DAMAGE, LEN(NM_MATERIAL_DAMAGE)-2))						AS NM_MATERIAL_DAMAGE
	,CONVERT(FLOAT,LEFT(NM_MORAL_DAMAGE, LEN(NM_MORAL_DAMAGE)-2))							AS NM_MORAL_DAMAGE
	,LEFT(NM_NOTIFICATION_RECEIVED,LEN(NM_NOTIFICATION_RECEIVED)-1)							AS NM_NOTIFICATION_RECEIVED
	,LEFT(NM_NOTIFICATION_RECEIVED_T,LEN(NM_NOTIFICATION_RECEIVED_T)-1)						AS NM_NOTIFICATION_RECEIVED_T
	,CONVERT(FLOAT,LEFT(NM_INVOICE_VALUE, LEN(NM_INVOICE_VALUE)-2))							AS NM_INVOICE_VALUE
	,CONVERT(FLOAT,LEFT(NM_LITIGATION_COST, LEN(NM_LITIGATION_COST)-2))						AS NM_LITIGATION_COST
	,CONVERT(FLOAT,LEFT(NM_COMPENSATION_AMOUNT_1, LEN(NM_COMPENSATION_AMOUNT_1)-2))			AS NM_COMPENSATION_AMOUNT_1
	,CONVERT(INT,LEFT(NM_CASE_STATUS,LEN(NM_CASE_STATUS)-1))								AS NM_CASE_STATUS
	,LEFT(NM_CASE_STATUS_T,LEN(NM_CASE_STATUS_T)-1)											AS NM_CASE_STATUS_T
	,LEFT(NM_MEDIATION_FAILURE,LEN(NM_MEDIATION_FAILURE)-1)									AS NM_MEDIATION_FAILURE
	,LEFT(NM_MEDIATION_FAILURE_T,LEN(NM_MEDIATION_FAILURE_T)-1)								AS NM_MEDIATION_FAILURE_T
	,LEFT(NM_WAITING_REASON,LEN(NM_WAITING_REASON)-1)										AS NM_WAITING_REASON
	,LEFT(NM_WAITING_REASON_T,LEN(NM_WAITING_REASON_T)-1)									AS NM_WAITING_REASON_T
	,LEFT(NM_FULFILLMENT_RESOLUTION,LEN(NM_FULFILLMENT_RESOLUTION)-1)						AS NM_FULFILLMENT_RESOLUTION
	,LEFT(NM_FULFILLMENT_RESOLUTION_T,LEN(NM_FULFILLMENT_RESOLUTION_T)-1)					AS NM_FULFILLMENT_RESOLUTION_T
	,LEFT(NM_ADDITIONAL_RESOLUTION,LEN(NM_ADDITIONAL_RESOLUTION)-1)							AS NM_ADDITIONAL_RESOLUTION
	,LEFT(NM_ADDITIONAL_RESOLUTION_T,LEN(NM_ADDITIONAL_RESOLUTION_T)-1)						AS NM_ADDITIONAL_RESOLUTION_T
	,LEFT(NM_COMPLETE_TYPE,LEN(NM_COMPLETE_TYPE)-1)											AS NM_COMPLETE_TYPE
	,LEFT(NM_COMPLETE_TYPE_T,LEN(NM_COMPLETE_TYPE_T)-1)										AS NM_COMPLETE_TYPE_T
	,LEFT(NM_COMPLETE_TEXT,LEN(NM_COMPLETE_TEXT)-1)											AS NM_COMPLETE_TEXT
	,CONVERT(FLOAT,LEFT(NM_FINAL_VALUE, LEN(NM_FINAL_VALUE)-2))								AS NM_FINAL_VALUE
	,CONVERT(FLOAT,LEFT(NM_FINAL_MATERIAL_DAMAGE, LEN(NM_FINAL_MATERIAL_DAMAGE)-2))			AS NM_FINAL_MATERIAL_DAMAGE
	,CONVERT(FLOAT,LEFT(NM_FINAL_MORAL_DAMAGE, LEN(NM_FINAL_MORAL_DAMAGE)-2))				AS NM_FINAL_MORAL_DAMAGE
	,LEFT(NM_MEDIATION_JUDGEMENT_TEXT,LEN(NM_MEDIATION_JUDGEMENT_TEXT)-1)					AS NM_MEDIATION_JUDGEMENT_TEXT
	,CONVERT(FLOAT,LEFT(NM_FINAL_LITIGATION_COST, LEN(NM_FINAL_LITIGATION_COST)-2))			AS NM_FINAL_LITIGATION_COST	
	,CONVERT(FLOAT,LEFT(NM_FINAL_COMPENSATION_AMOUNT, LEN(NM_FINAL_COMPENSATION_AMOUNT)-2))	AS NM_FINAL_COMPENSATION_AMOUNT	
	,LEFT(NM_LOS,LEN(NM_LOS)-1)																AS NM_LOS
	,LEFT(NM_COPY_OF_CHEQUE,LEN(NM_COPY_OF_CHEQUE)-1)										AS NM_COPY_OF_CHEQUE
	,LEFT(NM_WITHDRAWAL_ORDER,LEN(NM_WITHDRAWAL_ORDER)-1)									AS NM_WITHDRAWAL_ORDER
	,LEFT(NM_SETTLEMENT_LETTER,LEN(NM_SETTLEMENT_LETTER)-1)									AS NM_SETTLEMENT_LETTER
	,LEFT(NM_CLOSURE_ORDER,LEN(NM_CLOSURE_ORDER)-1)											AS NM_CLOSURE_ORDER
	,TRY_CONVERT(DATE,NM_AGREED_FULFILLMENT_DATE,103)										AS NM_AGREED_FULFILLMENT_DATE
	,LEFT(NM_REPRESENTATIVE,LEN(NM_REPRESENTATIVE)-1)										AS NM_REPRESENTATIVE
	,CONVERT(FLOAT,LEFT(NM_LAWYER_COST, LEN(NM_LAWYER_COST)-2))								AS NM_LAWYER_COST
	,TRY_CONVERT(DATE,NM_DEPOSIT_DATE,103)													AS NM_DEPOSIT_DATE
	,CONVERT(FLOAT,LEFT(NM_DEPOSIT_AMOUNT, LEN(NM_DEPOSIT_AMOUNT)-2))						AS NM_DEPOSIT_AMOUNT
	,LEFT(NM_PAYMENT_TYPE,LEN(NM_PAYMENT_TYPE)-1)											AS NM_PAYMENT_TYPE
	,LEFT(NM_PAYMENT_TYPE_T,LEN(NM_PAYMENT_TYPE_T)-1)										AS NM_PAYMENT_TYPE_T
	,LEFT(NM_REIMBURSE,LEN(NM_REIMBURSE)-1)													AS NM_REIMBURSE
	,LEFT(NM_REIMBURSE_TYPE,LEN(NM_REIMBURSE_TYPE)-1)										AS NM_REIMBURSE_TYPE
	,LEFT(NM_REIMBURSE_TYPE_T,LEN(NM_REIMBURSE_TYPE_T)-1)									AS NM_REIMBURSE_TYPE_T
	,LEFT(NM_CURRENCY_2,LEN(NM_CURRENCY_2)-1)												AS NM_CURRENCY_2
	,LEFT(NM_PRIORITY_REASON,LEN(NM_PRIORITY_REASON)-1)										AS NM_PRIORITY_REASON
	,LEFT(NM_PRIORITY_REASON_T,LEN(NM_PRIORITY_REASON_T)-1)									AS NM_PRIORITY_REASON_T
	,TRY_CONVERT(DATE,NM_AGREED_ETD_DATE,103)												AS NM_AGREED_ETD_DATE
	,LEFT(NM_DEPT_INCHARGE,LEN(NM_DEPT_INCHARGE)-1)											AS NM_DEPT_INCHARGE
	,LEFT(NM_DEPT_INCHARGE_T,LEN(NM_DEPT_INCHARGE_T)-1)										AS NM_DEPT_INCHARGE_T
	,LEFT(NM_ROOT_CAUSE,LEN(NM_ROOT_CAUSE)-1)												AS NM_ROOT_CAUSE
	,LEFT(NM_ROOT_CAUSE_T,LEN(NM_ROOT_CAUSE_T)-1)											AS NM_ROOT_CAUSE_T
	,LEFT(NM_TRUE_STATUS,LEN(NM_TRUE_STATUS)-1)												AS NM_TRUE_STATUS
	,LEFT(NM_TRUE_STATUS_T,LEN(NM_TRUE_STATUS_T)-1)											AS NM_TRUE_STATUS_T
	,LEFT(NM_TRUE_REASON,LEN(NM_TRUE_REASON)-1)												AS NM_TRUE_REASON
	,LEFT(NM_TRUE_REASON_T,LEN(NM_TRUE_REASON_T)-1)											AS NM_TRUE_REASON_T
	,LEFT(NM_ENGINEER,LEN(NM_ENGINEER)-1)													AS NM_ENGINEER
	,LEFT(NM_ENGINEER_T_1,LEN(NM_ENGINEER_T_1)-1)											AS NM_ENGINEER_T_1
	,CONVERT(INT,LEFT(NM_CUSTOMER_PERSPECTIVE,LEN(NM_CUSTOMER_PERSPECTIVE)-1))				AS NM_CUSTOMER_PERSPECTIVE
	,LEFT(NM_CUSTOMER_PERSPECTIVE_T,LEN(NM_CUSTOMER_PERSPECTIVE_T)-1)						AS NM_CUSTOMER_PERSPECTIVE_T
	,LEFT(NM_CUSTOMER_SIDE,LEN(NM_CUSTOMER_SIDE)-1)											AS NM_CUSTOMER_SIDE
	,LEFT(NM_SAMSUNG_SIDE,LEN(NM_SAMSUNG_SIDE)-1)											AS NM_SAMSUNG_SIDE
	,TRY_CONVERT(DATE,NM_CUSTOMER_DATE,103)													AS NM_CUSTOMER_DATE
	,TRY_CONVERT(DATE,NM_SAMSUNG_DATE,103)													AS NM_SAMSUNG_DATE
	,LEFT(NM_SERVICE_ORDER_NO,LEN(NM_SERVICE_ORDER_NO)-1)									AS NM_SERVICE_ORDER_NO
	,LEFT(NM_CONTACT,LEN(NM_CONTACT)-1)														AS NM_CONTACT
	,LEFT(NM_REDO_SERVICE_ORDER,LEN(NM_REDO_SERVICE_ORDER)-1)								AS NM_REDO_SERVICE_ORDER
	,LEFT(NM_CREATED_BY,LEN(NM_CREATED_BY)-1)												AS NM_CREATED_BY
	,CONVERT(DATETIME2(0),LEFT(NM_CREATED_AT,LEN(NM_CREATED_AT)-1),103)						AS NM_CREATED_AT
	,LEFT(NM_ASC_CODE_2,LEN(NM_ASC_CODE_2)-2)												AS NM_ASC_CODE_2
	,LEFT(NM_ASC_NAME_2,LEN(NM_ASC_NAME_2)-1)												AS NM_ASC_NAME_2
	,LEFT(NM_CHANGED_BY_2,LEN(NM_CHANGED_BY_2)-1)											AS NM_CHANGED_BY_2
	,CONVERT(DATETIME2(0),LEFT(NM_CHANGED_AT_2,LEN(NM_CHANGED_AT_2)-1),103)					AS NM_CHANGED_AT_2
	,LEFT(NM_SYMPTOM_1,LEN(NM_SYMPTOM_1)-1)													AS NM_SYMPTOM_1
	,LEFT(NM_SYMPTOM_2,LEN(NM_SYMPTOM_2)-1)													AS NM_SYMPTOM_2
	,LEFT(NM_SYMPTOM_3,LEN(NM_SYMPTOM_3)-1)													AS NM_SYMPTOM_3
	,LEFT(NM_DETAIL_TYPE_T,LEN(NM_DETAIL_TYPE_T)-1)											AS NM_DETAIL_TYPE_T
	,LEFT(NM_SERVICE_TYPE_T,LEN(NM_SERVICE_TYPE_T)-1)										AS NM_SERVICE_TYPE_T
	,LEFT(NM_SUB_SERVICE_TYPE_T,LEN(NM_SUB_SERVICE_TYPE_T)-1)								AS NM_SUB_SERVICE_TYPE_T
	,LEFT(NM_SERVICE_CHANNEL,LEN(NM_SERVICE_CHANNEL)-1)										AS NM_SERVICE_CHANNEL
	,LEFT(NM_STATUS_T_2,LEN(NM_STATUS_T_2)-1)												AS NM_STATUS_T_2
	,LEFT(NM_REASON_T,LEN(NM_REASON_T)-1)													AS NM_REASON_T
	,LEFT(NM_COMMENT,LEN(NM_COMMENT)-1)														AS NM_COMMENT
	,LEFT(NM_ENGINGEER,LEN(NM_ENGINGEER)-1)													AS NM_ENGINGEER
	,LEFT(NM_ENGINEER_T_2,LEN(NM_ENGINEER_T_2)-1)											AS NM_ENGINEER_T_2
	,LEFT(NM_ASC_ENGINEER,LEN(NM_ASC_ENGINEER)-1)											AS NM_ASC_ENGINEER
	,TRY_CONVERT(DATE,NM_ENGINEER_ASSIGN_DATE,103)											AS NM_ENGINEER_ASSIGN_DATE
	,TRY_CONVERT(DATE,NM_REPAIR_COMPLETE_DATE,103)											AS NM_REPAIR_COMPLETE_DATE
	,LEFT(NM_RMA_NO,LEN(NM_RMA_NO)-1)														AS NM_RMA_NO
	,TRY_CONVERT(DATE,NM_RETURN_ORDER_DATE,103)												AS NM_RETURN_ORDER_DATE
	,LEFT(NM_WARRANTY_TERM,LEN(NM_WARRANTY_TERM)-1)											AS NM_WARRANTY_TERM
	,LEFT(NM_WARRANTY_EXCEPTION,LEN(NM_WARRANTY_EXCEPTION)-1)								AS NM_WARRANTY_EXCEPTION
	,LEFT(NM_EX_REFUND_REASON,LEN(NM_EX_REFUND_REASON)-1)									AS NM_EX_REFUND_REASON
	,LEFT(NM_SUB_REASON,LEN(NM_SUB_REASON)-1)												AS NM_SUB_REASON
	,LEFT(NM_DELIVERY_TYPE_T,LEN(NM_DELIVERY_TYPE_T)-1)										AS NM_DELIVERY_TYPE_T
	,LEFT(NM_CURRENCY_3,LEN(NM_CURRENCY_3)-1)												AS NM_CURRENCY_3
	,CONVERT(FLOAT,LEFT(NM_REFUND_AMOUNT, LEN(NM_REFUND_AMOUNT)-2))							AS NM_REFUND_AMOUNT
	,CONVERT(FLOAT,LEFT(NM_COMPENSATION_AMOUNT_2, LEN(NM_COMPENSATION_AMOUNT_2)-2))			AS NM_COMPENSATION_AMOUNT_2
	,CONVERT(FLOAT,LEFT(NM_EXCHANGE_FEE, LEN(NM_EXCHANGE_FEE)-2))							AS NM_EXCHANGE_FEE
	,CONVERT(FLOAT,LEFT(NM_ESTIMATED_REPAIR_COST, LEN(NM_ESTIMATED_REPAIR_COST)-2))			AS NM_ESTIMATED_REPAIR_COST
FROM DB_SAMSUNG.DBO.TB_STG_SAMS_VOCS
END;