CREATE PROCEDURE dbo.PRC_SAMS_CARGA_VOCS_REPORT AS

BEGIN

DELETE  TB_SAMS_VOCS_REPORT FROM TB_SAMS_VOCS_REPORT
INNER JOIN TB_STG_SAMS_VOCS_REPORT 
	ON TB_SAMS_VOCS_REPORT.NM_REF_TICKET = TB_STG_SAMS_VOCS_REPORT.NM_REF_TICKET AND TB_SAMS_VOCS_REPORT.NM_TICKET_NO = TB_STG_SAMS_VOCS_REPORT.NM_TICKET_NO
WHERE TB_SAMS_VOCS_REPORT.NM_REF_TICKET = TB_STG_SAMS_VOCS_REPORT.NM_REF_TICKET AND TB_SAMS_VOCS_REPORT.NM_TICKET_NO = TB_STG_SAMS_VOCS_REPORT.NM_TICKET_NO

INSERT INTO DBO.TB_SAMS_VOCS_REPORT
(
	 NM_REF_TICKET
	,NM_CLAIM_TYPE_1
	,NM_CLAIM_TYPE_DESC_1
	,NM_TICKET_NO
	,DT_POSTING_DATE
	,NM_PROCESS_TYPE
	,NM_PROCESS_TYPE_DESC
	,NM_DETAIL_TYPE_1
	,NM_DETAIL_TYPE_2
	,NM_SERVICE_TYPE
	,NM_STATUS
	,NM_STATUS_DESC
	,NM_CLAIM_TYPE_2
	,NM_CLAIM_TYPE_DESC_2
	,NM_SOLUTION
	,NM_SOLUTION_DESC
	,NM_SUB_SOLUTION
	,NM_SUB_SOLUTION_DESC
	,DT_COMPLETE_DATE
	,NM_SERIAL_NO
	,NM_ASC_CODE
	,NM_ASC_NAME
	,NM_LINK_TYPE
)
SELECT 
	 NM_REF_TICKET
	,NM_CLAIM_TYPE_1
	,NM_CLAIM_TYPE_DESC_1
	,NM_TICKET_NO
	,CONVERT(DATE,NM_POSTING_DATE,103)	AS DT_POSTING_DATE
	,NM_PROCESS_TYPE
	,NM_PROCESS_TYPE_DESC
	,NM_DETAIL_TYPE_1
	,NM_DETAIL_TYPE_2
	,NM_SERVICE_TYPE
	,NM_STATUS
	,NM_STATUS_DESC
	,NM_CLAIM_TYPE_2
	,NM_CLAIM_TYPE_DESC_2
	,NM_SOLUTION
	,NM_SOLUTION_DESC
	,NM_SUB_SOLUTION
	,NM_SUB_SOLUTION_DESC
	,CONVERT(DATE,NM_COMPLETE_DATE,103)	AS DT_COMPLETE_DATE
	,NM_SERIAL_NO
	,NM_ASC_CODE
	,NM_ASC_NAME
	,NM_LINK_TYPE
FROM DB_SAMSUNG.DBO.TB_STG_SAMS_VOCS_REPORT
END;