SELECT 
	 CMS.[DATA]									AS DT_DATA
    ,CMS.[SKILL]								AS NR_SKILL
	,ADM.[NM_SKILL_NOME]                        AS NM_SKILL_NOME
    ,ADM.[NM_PILAR_NOME]                        AS NM_PILAR_NOME
    ,ADM.[NM_OPERACAO_NOME]						AS NM_OPERACAO_NOME
    ,ADM.[NM_CELULA_NOME]                       AS NM_CELULA_NOME
    ,ADM.[NM_SEGMENTO_NOME]						AS NM_SEGMENTO_NOME
    ,ADM.[NM_PROGRAMA_NOME]						AS NM_PROGRAMA_NOME
	,CMS.[HORARIO]								AS NR_HORARIO
    ,CMS.[CHAMS PERMS]							AS NR_CHAMS_PERMS
    ,CMS.[CHAMS ATEND]							AS NR_CHAMS_ATEND
    ,CMS.[NIVEL AT]								AS VL_NIVEL_AT
    ,CMS.[FCL09 AT]								AS VL_FCL09_AT
    ,CMS.[TMO(CMS)]								AS VL_TMO_CMS
    ,CMS.[TMO(SEG)]								AS VL_TMO_SEG
    ,CMS.[TME(CMS)]								AS VL_TME_CMS
    ,CMS.[TME(SEG)]								AS VL_TME_SEG
    ,CMS.[ATEND 0 - A2]							AS NR_ATEND_0_A_A2
    ,CMS.[ATEND A2 - A3]						AS NR_ATEND_A2_A_A3
    ,CMS.[ATEND A3 - A5]						AS NR_ATEND_A3_A_A5
    ,CMS.[ATEND > A5]							AS NR_ATEND_MAIOR_A5
    ,CMS.[ABAN 0 - A2]							AS NR_ABAN_0_A_A2
    ,CMS.[ABAN > A5]							AS NR_ABAN_MAIOR_A5
    ,CMS.[CHAMS ABAND]							AS NR_CHAMS_ABAND
    ,CMS.[TEMPO DAC (SEG)]						AS NR_TEMPO_DAC_SEG
    ,CMS.[TEMPO POS_AT (SEG)]					AS NR_TEMPO_POS_AT_SEG
    ,CMS.[TEMPO TOCANDO (SEG)]					AS NR_TEMPO_TOCANDO_SEG
    ,CMS.[TEMPO HOLD (SEG)]						AS NR_TEMPO_HOLD_SEG
    ,CMS.[TRANS EXT]							AS NR_TRANS_EXT
    ,CMS.[ATEND > A6]							AS NR_ATEND_MAIOR_A6
    ,CMS.[ABAN > A6]							AS NR_ABAN_MAIOR_A6
    ,CMS.[TOTAL ATEND ATE A1]					AS NR_TOTAL_ATEND_ATE_A1
    ,CMS.[TOTAL ATEND ATE A2]					AS NR_TOTAL_ATEND_ATE_A2
    ,CMS.[TOTAL ATEND ATE A3]					AS NR_TOTAL_ATEND_ATE_A3
    ,CMS.[TOTAL ATEND ATE A4]					AS NR_TOTAL_ATEND_ATE_A4
    ,CMS.[TOTAL ATEND ATE A5]					AS NR_TOTAL_ATEND_ATE_A5
    ,CMS.[TOTAL ATEND ATE A6]					AS NR_TOTAL_ATEND_ATE_A6
    ,CMS.[TOTAL ABAND ATE A1]					AS NR_TOTAL_ABAND_ATE_A1
    ,CMS.[TOTAL ABAND ATE A2]					AS NR_TOTAL_ABAND_ATE_A2
    ,CMS.[TOTAL ABAND ATE A3]					AS NR_TOTAL_ABAND_ATE_A3
    ,CMS.[TOTAL ABAND ATE A4]					AS NR_TOTAL_ABAND_ATE_A4
    ,CMS.[TOTAL ABAND ATE A5]					AS NR_TOTAL_ABAND_ATE_A5
    ,CMS.[TOTAL ABAND ATE A6]					AS NR_TOTAL_ABAND_ATE_A6
    ,CMS.[CHAM FORA DA CENTRAL]					AS NR_CHAM_FORA_DA_CENTRAL
    ,CMS.[TEMPO MEDIO FORA DA CENTRAL (SEG)]	AS VL_TEMPO_MEDIO_FORA_DA_CENTRAL_SEG
    ,CMS.[TEMPO DAC FORA DA CENTRAL (SEG)]		AS NR_TEMPO_DAC_FORA_DA_CENTRAL_SEG
    ,CMS.[CHAMS RAMAL SAIDA]					AS NR_CHAMS_RAMAL_SAIDA
    ,CMS.[TEMPO MEDIO RAMAL SAIDA (SEG)]		AS VL_TEMPO_MEDIO_RAMAL_SAIDA_SEG
    ,CMS.[TEMPO RAMAL SAIDA (SEG)]				AS NR_TEMPO_RAMAL_SAIDA_SEG
    ,CMS.[ANSTIME (SEG)]						AS NR_ANSTIME_SEG
    ,CMS.[CHAMS OCUP FORCADO]					AS NR_CHAMS_OCUP_FORCADO
    ,CMS.[CHAMS RVDAS FILAS]					AS NR_CHAMS_RVDAS_FILAS
    ,CMS.[CHAMS DESC FORCADA]					AS NR_CHAMS_DESC_FORCADA
    ,CMS.[FLUXO SAIDA]							AS NR_FLUXO_SAIDA
    ,CMS.[CHAM CONF]							AS NR_CHAM_CONF
    ,CMS.[CHAM ATEND ACEITAVEL]					AS NR_CHAM_ATEND_ACEITAVEL
    ,CMS.[CHAM ABAND ACEITAVEL]					AS NR_CHAM_ABAND_ACEITAVEL
    ,CMS.[TEMPO MAXIMO DE ESPERA]				AS NR_TEMPO_MAXIMO_DE_ESPERA
    ,CMS.[TEMPO MED ABAN (SEG)]					AS VL_TEMPO_MED_ABAN_SEG
FROM [DB_REP_CMS].[DBO].[10_155_0_93_SAMSUNG_DESEMP_SERV_INTERV_GR_DIV_MIS_01] AS CMS
LEFT JOIN  (SELECT 
	ROW_NUMBER() OVER(PARTITION BY [SKILL_CODIGO] ORDER BY SKILL_HIERARQUIA_ID DESC, OPERACAO_ID DESC) AS NR_ORDEM
    ,[SKILL_ID]									AS NR_SKILL_ID
    ,[SKILL_CODIGO]								AS NM_SKILL_CODIGO
    ,[SKILL_NOME]								AS NM_SKILL_NOME
    ,[SKILL_SITE]								AS NM_SKILL_SITE
    ,[SKILL_DAC]								AS NR_SKILL_DAC
    ,[DAC_SITE_NOME]							AS NM_DAC_SITE_NOME
    ,[DAC_ATIVO]								AS NM_DAC_ATIVO
    ,[DAC_CRIADO_EM]							AS DT_DAC_CRIADO_EM
    ,[PILAR_NOME]								AS NM_PILAR_NOME
    ,[OPERACAO_NOME]							AS NM_OPERACAO_NOME
    ,[CELULA_NOME]								AS NM_CELULA_NOME
    ,[SEGMENTO_NOME]							AS NM_SEGMENTO_NOME
    ,[PROGRAMA_NOME]							AS NM_PROGRAMA_NOME
    ,[PROGRAMA_VIGENCIA_INICIO]					AS DT_PROGRAMA_VIGENCIA_INICIO
    ,[PROGRAMA_VIGENCIA_FIM]					AS DT_PROGRAMA_VIGENCIA_FIM
    ,[PROGRAMA_DIRETORIA_EXEC_BI_NOME]			AS NM_PROGRAMA_DIRETORIA_EXEC_BI_NOME	
    ,[PROGRAMA_DAC_ID]							AS NR_PROGRAMA_DAC_ID
    ,[PROGRAMA_DAC_NOME]						AS NM_PROGRAMA_DAC_NOME
    ,[PROGRAMA_ATIVO]							AS NM_PROGRAMA_ATIVO
    ,[ORGANIZACAO_NOME]							AS NM_ORGANIZACAO_NOME
    ,[ORGANIZACAO_WFM]							AS NM_ORGANIZACAO_WFM
    ,[ORGANIZACAO_CRIADO_EM]					AS DT_ORGANIZACAO_CRIADO_EM
    ,[ORGANIZACAO_ATIVO]						AS NM_ORGANIZACAO_ATIVO
FROM
	[DB_REP_ADM].[DBO].[VW_PROGRAMA_SKILL]
WHERE 
	[DIRETORIA_NOME] LIKE '%SAMS%')	AS ADM
	ON CMS.[SKILL] = ADM.[NM_SKILL_CODIGO]
WHERE 
	ADM.NR_ORDEM = 1
	AND CONVERT(DATE, CMS.[DATA], 103) >= DATEADD(D, -10, CONVERT(DATE, GETDATE(), 103))