IF OBJECT_ID('TEMPDB..#DATAS_RMA_FOLLOW') IS NOT NULL 
	DROP TABLE #DATAS_RMA_FOLLOW
IF OBJECT_ID('TEMPDB..#BASE_DATAS') IS NOT NULL 
	DROP TABLE #BASE_DATAS
IF OBJECT_ID('TEMPDB..#RANGE_DATAS') IS NOT NULL 
	DROP TABLE #RANGE_DATAS
IF OBJECT_ID('TEMPDB..#TMP_TB_RMA_FOLLOW') IS NOT NULL 
	DROP TABLE #TMP_TB_RMA_FOLLOW
IF OBJECT_ID('TEMPDB..#BASE_STA') IS NOT NULL 
	DROP TABLE #BASE_STA

	
GO
	SELECT NM_TICKET, MAX(DT_DATA_BASE) AS DATA_FIM, MIN(DT_DATA_BASE) AS DATA_INI
	INTO #DATAS_RMA_FOLLOW
	FROM [DB_SAMSUNG].[dbo].[TB_SAMSUMG_SAP_RMA_FOLLOW] WITH (NOLOCK)
	GROUP BY NM_TICKET

	SELECT ROW_NUMBER() OVER(ORDER BY DT_DATA_BASE) POS
		,DT_DATA_BASE AS DT_BASE
	INTO #BASE_DATAS
	FROM [DB_SAMSUNG].[dbo].[TB_SAMSUMG_SAP_RMA_FOLLOW] WITH (NOLOCK)
	GROUP BY DT_DATA_BASE
--RANGE DE DATAS DE CRIACAO E FINALIZACAO
	SELECT DATA1.POS, DATA1.DT_BASE, DATA0.DT_BASE AS DT_ANT
	INTO #RANGE_DATAS
	FROM #BASE_DATAS AS DATA1
	LEFT JOIN #BASE_DATAS AS DATA0
	ON DATA1.POS = DATA0.POS + 1
	GROUP BY  DATA1.DT_BASE, DATA0.DT_BASE, DATA1.POS, DATA0.POS
	ORDER BY 1
--MAIOR DATA DA BASE
	DECLARE @DATA_MAX AS DATE
	SET @DATA_MAX = (SELECT MAX(DT_BASE) FROM #RANGE_DATAS)
--CRIACAO DO RAW DATA DE RMA
	SELECT RMA.*
		, CASE WHEN RMA.DT_DATA_BASE = @DATA_MAX THEN NULL
			WHEN RMA.DT_DATA_BASE = B.DATA_FIM THEN B.DATA_FIM ELSE NULL END AS DT_FIM
		, CASE WHEN RMA.DT_DATA_BASE = C.DT_BASE THEN C.DT_ANT ELSE NULL END AS DT_INI
	INTO #TMP_TB_RMA_FOLLOW	
	FROM [DB_SAMSUNG].[dbo].[TB_SAMSUMG_SAP_RMA_FOLLOW] RMA WITH (NOLOCK)
	LEFT JOIN #DATAS_RMA_FOLLOW B
		ON RMA.[NM_TICKET] = B.NM_TICKET
	LEFT JOIN #RANGE_DATAS C
		ON B.DATA_INI = C.DT_BASE

--BASE STA
	SELECT
		ROW_NUMBER() OVER(PARTITION BY  [ST_COD_IDENTIFICADOR], CONVERT(DATE, [DT_TABULACAO], 103)  ORDER BY [DT_TABULACAO] DESC) ORDEM
		,[ST_COD_IDENTIFICADOR]
		  ,CONVERT(DATE, [DT_TABULACAO], 103) [DT_TABULACAO]
		  ,[SUPERVISOR]
		  ,[OPERADOR]
		  ,[STATUS_PAI]
		  ,[STATUS_FILHO]
		  ,[ATIVIDADE]
	INTO #BASE_STA
	FROM [DB_OUTROS].[dbo].[TB_SAMS_STA_BACKOFFICE]
	WHERE ([DSC_ESPECIALIDADE] LIKE 'RMA%'OR ST_NOM_CAMPANHA LIKE 'RMA%')
	AND [STATUS_PAI] = 'FINALIZADO'
	AND LEN([ST_COD_IDENTIFICADOR]) = 10	

--CRIACAO DE TABELA PARA POWER BI
	TRUNCATE TABLE [DB_SAMSUNG].[dbo].[TB_FAT_MIS80280_RMA_FOLLOW_PBI]
	INSERT INTO [DB_SAMSUNG].[dbo].[TB_FAT_MIS80280_RMA_FOLLOW_PBI]
	(
		D_DATA
		,M_QTD_PEND
		,M_QTD_FNALZD
		,M_QTDE_ENTRD
		,M_PEND_ATE_3DIA
		,M_PEND_ATE_5DIA
		,M_PEND_MAIOR_3DIA
		,M_PEND_MAIOR_5DIA
		,M_PEND_MAIOR_7DIA
		,M_PEND_MAIOR_18DIA
		,M_PEND_MAX
		,DT_ATUALIZACAO
	)

	SELECT
		BASE_A.[DT_DATA_BASE] AS [D_DATA]
		, COUNT(BASE_A.[DT_DATA_BASE]) AS [M_QTD_PEND]
		, SUM(CASE WHEN BASE_A.DT_FIM IS NOT NULL THEN 1 ELSE 0 END) AS [M_QTD_FNALZD]
		, BASE_B.QTD_ENTRADA [M_QTDE_ENTRD]
		, SUM(CASE WHEN DATEDIFF(D, DT_POSTING_DATE, BASE_A.[DT_DATA_BASE])<= 3 THEN 1 ELSE 0 END) [M_PEND_ATE_3DIA]
		, SUM(CASE WHEN DATEDIFF(D, DT_POSTING_DATE, BASE_A.[DT_DATA_BASE])<= 5 THEN 1 ELSE 0 END) [M_PEND_ATE_5DIA]
		, SUM(CASE WHEN DATEDIFF(D, DT_POSTING_DATE, BASE_A.[DT_DATA_BASE])> 3 THEN 1 ELSE 0 END) [M_PEND_MAIOR_3DIA]
		, SUM(CASE WHEN DATEDIFF(D, DT_POSTING_DATE, BASE_A.[DT_DATA_BASE])> 5 THEN 1 ELSE 0 END) [M_PEND_MAIOR_5DIA]
		, SUM(CASE WHEN DATEDIFF(D, DT_POSTING_DATE, BASE_A.[DT_DATA_BASE])> 7 THEN 1 ELSE 0 END) [M_PEND_MAIOR_7DIA]
		, SUM(CASE WHEN DATEDIFF(D, DT_POSTING_DATE, BASE_A.[DT_DATA_BASE]) > 18 THEN 1 ELSE 0 END) [M_PEND_MAIOR_18DIA]
		, MAX(DATEDIFF(D, DT_POSTING_DATE, BASE_A.[DT_DATA_BASE])) [M_PEND_MAX]
		, GETDATE() AS [DT_ATUALIZACAO]
	FROM #TMP_TB_RMA_FOLLOW BASE_A
	LEFT JOIN (SELECT DT_INI, COUNT(DT_INI) AS QTD_ENTRADA FROM #TMP_TB_RMA_FOLLOW WHERE DT_INI IS NOT NULL GROUP BY DT_INI) BASE_B
		ON BASE_A.[DT_DATA_BASE] = BASE_B.DT_INI 
	GROUP BY BASE_A.[DT_DATA_BASE], BASE_B.DT_INI, QTD_ENTRADA 
	ORDER BY 1


--TB_FAT_MIS80280_RMA_FOLLOW_FINALIZADOS_PBI

SELECT * FROM #TMP_TB_RMA_FOLLOW AS RMA
LEFT JOIN #BASE_STA AS STA 
	ON RMA.DT_FIM = STA.DT_TABULACAO  AND RMA.NM_TICKET  = STA.ST_COD_IDENTIFICADOR
WHERE (STA.ORDEM = 1 OR STA.ORDEM IS NULL)
	AND RMA.DT_FIM IS NOT NULL

