USE [DB_CONSUMO]
GO

/****** Object:  View [dbo].[VW_SAMS_VOC_REPORT_RAW_DATA]    Script Date: 12/12/2019 17:50:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[VW_SAMS_VOC_REPORT_RAW_DATA]
AS

SELECT 
	--ROW_NUMBER() OVER(PARTITION BY V.[TRANSACTION ID] ORDER BY V.[TRANSACTION ID]) ORDEM,
	V.* 
	,CASE WHEN T2.TIPO = 'GRMS' THEN 'SIM' ELSE NULL END AS [GRMS]
	,CASE WHEN T2.TIPO IS NULL  THEN NULL
		WHEN  R.[Ref# Ticket] IS NOT NULL AND CONVERT(DATE, R.[Posting Date], 103) >= V.[AGREED DATE] THEN 'SIM' 
		
	ELSE 'NÃO' END AS [ACORDO CRIADO]
	,CASE WHEN R2.[Claim Type Desc4] LIKE 'COURT%' AND CONVERT(DATE, R2.[Posting Date], 103) >= V.[Posting Date] THEN 'SIM' ELSE NULL END AS 'COURT' 
	,CASE WHEN R2.[Claim Type Desc4] LIKE 'Procon (AUD)' AND CONVERT(DATE, R2.[Posting Date], 103) >= V.[Posting Date] THEN 'SIM' ELSE NULL END AS 'AUD' 


FROM [DB_OUTROS].[dbo].[TB_SAMS_VOC_REPORT_CONSOLIDADO] V WITH (NOLOCK)

LEFT JOIN [DB_DEPARA].[dbo].[TB_SAMS_DP_SOLUTIONS] T2 WITH (NOLOCK)
ON REPLACE(V.[Completed Solution I_T],' ','') = T2.[COMPLETED SOLUTION]

LEFT JOIN [DB_CONSUMO].dbo.[VW_SAMS_VOC_REPORT_ACORDOS_REPORT03] R WITH (NOLOCK) 
ON LEFT(V.[TRANSACTION ID], 10) = R.[Ref# Ticket]

LEFT JOIN [DB_CONSUMO].dbo.[VW_SAMS_VOC_REPORT_HEAVY_CLAIM_REPORT03] R2 WITH (NOLOCK) 
ON LEFT(V.[TRANSACTION ID], 10) = R2.[Ref# Ticket]



GO

select * from [DB_DEPARA].[dbo].[TB_SAMS_DP_SOLUTIONS]
