

CREATE PROCEDURE INPORT_XLS_PROPOSTA AS
BEGIN
	EXEC [dbo].[INPORT_XLS_PROPOSTA_ANGELONI]
	EXEC [dbo].[INPORT_XLS_PROPOSTA_COOP]
	EXEC [dbo].[INPORT_XLS_PROPOSTA_LASA]
	EXEC [dbo].[INPORT_XLS_PROPOSTA_MAKRO]
	EXEC [dbo].[INPORT_XLS_PROPOSTA_SODIMAC]
END


EXEC INPORT_XLS_PROPOSTA