

CREATE PROCEDURE INPORT_XLS_PREVIA_APROVADA AS
BEGIN
	EXEC [dbo].[INPORT_XLS_PREVIA_APROVADA_ANGELONI]
	EXEC [dbo].[INPORT_XLS_PREVIA_APROVADA_COOP]
	EXEC [dbo].[INPORT_XLS_PREVIA_APROVADA_LASA]
	EXEC [dbo].[INPORT_XLS_PREVIA_APROVADA_MAKRO]
	EXEC [dbo].[INPORT_XLS_PREVIA_APROVADA_SODIMAC]
END


EXEC INPORT_XLS_PREVIA_APROVADA