

CREATE PROCEDURE INPORT_XLS_CONSULTA_PREVIA AS
BEGIN												
	EXEC [dbo].[INPORT_XLS_CONSULTA_PREVIA_ANGELONI]
	EXEC [dbo].[INPORT_XLS_CONSULTA_PREVIA_COOP]
	EXEC [dbo].[INPORT_XLS_CONSULTA_PREVIA_LASA]
	EXEC [dbo].[INPORT_XLS_CONSULTA_PREVIA_MAKRO]
	EXEC [dbo].[INPORT_XLS_CONSULTA_PREVIA_SODIMAC]		
END


EXEC INPORT_XLS_CONSULTA_PREVIA