
/* HABILITANDO INSTANCIAS
USE [master]
--CONFIGURANDO À INSTÂNCIA SQL PARA ACEITAR OPÇÕES AVANÇADAS
EXEC sp_configure 'show advanced options', 1
RECONFIGURE
--HABILITANDO O USO DE CONSULTAS DISTRIBUÍDAS
EXEC sp_configure 'Ad Hoc Distributed Queries', 1
RECONFIGURE
--ADICIONANDO OS DRIVERS NA INSTÂNCIA SQL
EXEC master.dbo.sp_MSset_oledb_prop N'Microsoft.ACE.OLEDB.12.0', N'AllowInProcess', 1
EXEC master.dbo.sp_MSset_oledb_prop N'Microsoft.ACE.OLEDB.12.0', N'DynamicParameters', 1
*/
USE BRA_SOLUCOES_PDV

CREATE PROCEDURE INPORT_XLS_ADESAO_ANGELONI AS
BEGIN

--- CRIAÇÃO DA TABELA TEMPORÁRIA
	IF OBJECT_ID('TEMPDB..#BASE_XLS') IS NOT NULL
			BEGIN
				DROP TABLE #BASE_XLS
			END;

	CREATE TABLE #BASE_XLS
		(
			CODIGO_PARCEIRO		VARCHAR(10),
			CODIGO_LOJA			VARCHAR(10),
			CODIGO_PROMOTOR		VARCHAR(20),
			ORG_LOGO			VARCHAR(10),
			MIGRACAO			VARCHAR	(1),
			DESCRITIVO			VARCHAR	(50),
			QUANTIDADE			INT,
			DATA_ACAO			DATE
		)

	DECLARE	@CONT					INT
	DECLARE	@INTERVALO_DIAS			INT
	DECLARE @DATA_FIM				DATE
	DECLARE @DATA_INICIO			DATE
	DECLARE @DATA_CABECALHO_INICIO	VARCHAR(8)
	DECLARE @DATA_CABECALHO_FIM		VARCHAR(8)
	DECLARE @DATA_CABECALHO_ARQUIVO	VARCHAR(10)

	--SELECIONANDO DATA INICIO EXTRAÇÃO
	SET @DATA_CABECALHO_INICIO =(SELECT TOP 1 SUBSTRING(RIGHT(LTRIM(RTRIM(F1)),21),1,8)
	FROM OPENROWSET (
		'Microsoft.ACE.OLEDB.12.0', 
		'Excel 12.0;Database=\\gru3wvamexdb1\Queries BI\2 - Monitorias\18 - Bradescard\BASES\ANGELONI_ADESÃO.XLS;HDR=NO', 
		'SELECT * FROM [Indicadores Diarios$]')WHERE F1 LIKE 'Indicadores%')
	--SELECT @DATA_CABECALHO_INICIO

	--SELECIONANDO DATA FIM EXTRAÇÃO
	SET @DATA_CABECALHO_FIM = (SELECT TOP 1 RIGHT(LTRIM(RTRIM(F1)),8)
	FROM OPENROWSET (
		'Microsoft.ACE.OLEDB.12.0', 
		'Excel 12.0;Database=\\gru3wvamexdb1\Queries BI\2 - Monitorias\18 - Bradescard\BASES\ANGELONI_ADESÃO.XLS;HDR=NO', 
		'SELECT * FROM [Indicadores Diarios$]')WHERE F1  LIKE 'Indicadores%')
	--SELECT @DATA_CABECALHO_FIM

	--SELECIONANDO DATA DE GERAÇÃO DA EXTRAÇÃO
	SET @DATA_CABECALHO_ARQUIVO = (SELECT TOP 1 SUBSTRING(LTRIM(RTRIM(F1)),11,10)
	FROM OPENROWSET (
		'Microsoft.ACE.OLEDB.12.0', 
		'Excel 12.0;Database=\\gru3wvamexdb1\Queries BI\2 - Monitorias\18 - Bradescard\BASES\ANGELONI_ADESÃO.XLS;HDR=NO', 
		'SELECT * FROM [Indicadores Diarios$]'
	)WHERE F1 LIKE 'Dados de:%')
	--SELECT @DATA_CABECALHO_ARQUIVO

	SET @CONT = 2
	SET @DATA_INICIO = CONVERT(DATE,'20' + SUBSTRING(@DATA_CABECALHO_INICIO,7,2) + '-' + SUBSTRING(@DATA_CABECALHO_INICIO,4,2) + '-' + SUBSTRING(@DATA_CABECALHO_INICIO,1,2))
	SET @DATA_FIM = CONVERT(DATE,'20' + SUBSTRING(@DATA_CABECALHO_FIM,7,2) + '-' + SUBSTRING(@DATA_CABECALHO_FIM,4,2) + '-' + SUBSTRING(@DATA_CABECALHO_FIM,1,2))
	SET @INTERVALO_DIAS = convert(INT,DATEDIFF(DAY, @DATA_INICIO,@DATA_FIM) +2)


--Função criada para separar letras de números e importar planilha para a tabela temporaria.
	while @CONT <= @INTERVALO_DIAS
		begin
		
	DECLARE @DATA_ARQUIVO DATE
	SET @DATA_ARQUIVO = CONVERT(DATE,SUBSTRING(@DATA_CABECALHO_ARQUIVO,7,4) + '-' + SUBSTRING(@DATA_CABECALHO_ARQUIVO,4,2) + '-' + SUBSTRING(@DATA_CABECALHO_ARQUIVO,1,2))
	--select @DATA_ARQUIVO

	DECLARE	@BUSCADOR_CAMPO	VARCHAR(4)
	SET @BUSCADOR_CAMPO = 'F' + CONVERT(VARCHAR,@CONT)
		
	DECLARE @DATA_ADESAO AS DATE
	SET @DATA_ADESAO = DATEADD(DD,@CONT-2,@DATA_INICIO)

	DECLARE @COMANDO_SQL VARCHAR(1000)
	SET @COMANDO_SQL =
	'INSERT INTO #BASE_XLS
			SELECT	''112''														AS CODIGO_PARCEIRO,
					left(F1, charindex('' '', F1)-1)							AS CODIGO_LOJA,	
					NULL														AS CODIGO_PROMOTOR,
					NULL														AS ORG_LOGO,
					NULL														AS MIGRACAO,
					''ADESÃO''													AS DESCRITIVO,
					' + @BUSCADOR_CAMPO + '										AS QUANTIDADE,
					' +  ''''+ CONVERT(VARCHAR,@DATA_ADESAO) + '''' + '			AS DATA_ACAO
			FROM OPENROWSET (''Microsoft.ACE.OLEDB.12.0'', 
			''Excel 12.0;Database=\\gru3wvamexdb1\Queries BI\2 - Monitorias\18 - Bradescard\BASES\ANGELONI_ADESÃO.XLS;HDR=NO'', 
			''SELECT * FROM [Indicadores Diarios$]'')
			WHERE F1 NOT LIKE ''%Total%''
				AND F2 IS NOT NULL 
				AND F3 IS NOT NULL
				AND F4 IS NOT NULL'
					
			--select(@COMANDO_SQL)
			EXEC(@COMANDO_SQL)
			Set @CONT = @CONT + 1
		end;

	--IMPORTANDO DA TABELA TEMPORARIA PARA A TABELA FISICA
	INSERT VENDA_DIARIA_NOVOFRONT 
		  select tp.*, CONVERT(DATE,GETDATE ()) AS DATA_IMPORTACAO_ARQUIVO, 'XLS' ARQUIVO_IMPORTACAO from #BASE_XLS  as tp 
			where  not  EXISTS (select * from VENDA_DIARIA_NOVOFRONT as tf 
									where	tf.DATA_ACAO		= CONVERT(DATE,tp.DATA_ACAO,103)
									AND		tf.CODIGO_PARCEIRO	= '112'
									AND		(tf.DESCRITIVO		= 'ADESÃO' OR tf.DESCRITIVO		= 'CONTAS APROVADAS'))															 
END;

--executa procedure
EXEC  INPORT_XLS_ADESAO_ANGELONI

/*
	SELECT * FROM VENDA_DIARIA_NOVOFRONT 
	WHERE CODIGO_PARCEIRO = 112
	ORDER BY DATA_ACAO DESC

	select	count(codigo_loja) AS qtde_loja,DATA_ACAO
	from VENDA_DIARIA_NOVOFRONT
	WHERE CODIGO_PARCEIRO = 112
	group by DATA_ACAO
	ORDER BY DATA_ACAO DESC
*/