

CREATE PROCEDURE INPORT_XLS_ADESAO AS
BEGIN
	EXEC [dbo].[INPORT_XLS_ADESAO_ANGELONI]
	EXEC [dbo].[INPORT_XLS_ADESAO_COOP]
	EXEC [dbo].[INPORT_XLS_ADESAO_LASA]
	EXEC [dbo].[INPORT_XLS_ADESAO_MAKRO]
	EXEC [dbo].[INPORT_XLS_ADESAO_SODIMAC]
END


EXEC INPORT_XLS_ADESAO