
CREATE PROCEDURE INPORT_XLS AS
BEGIN
	EXEC [dbo].[INPORT_XLS_ADESAO]
	EXEC [dbo].[INPORT_XLS_CONSULTA_PREVIA]
	EXEC [dbo].[INPORT_XLS_PREVIA_APROVADA]
	EXEC [dbo].[INPORT_XLS_PROPOSTA]
END

EXEC INPORT_XLS