use BRA_SOLUCOES_PDV

create procedure INPORT_TXT as
begin

	if OBJECT_ID('TEMPDB..#BASE_TXT') IS NOT NULL
		BEGIN
			DROP TABLE  #BASE_TXT
		END;
	
	create table #BASE_TXT
	(
	CODIGO_PARCEIRO	VARCHAR(10),
	CODIGO_LOJA		VARCHAR(10),
	CODIGO_PROMOTOR	VARCHAR(20),
	ORG_LOGO		VARCHAR(10),
	MIGRACAO		VARCHAR	(1),
	DESCRITIVO		VARCHAR	(50),
	QUANTIDADE		INT,
	DATA_ACAO		VARCHAR(10)
	)

	BULK INSERT #BASE_TXT
	FROM '\\gru3wvamexdb1\Queries BI\2 - Monitorias\18 - Bradescard\BASES\BASE_TXT.txt' 
	with (fieldterminator=';',CODEPAGE='ACP')

		  INSERT VENDA_DIARIA_NOVOFRONT 
			select tp.CODIGO_PARCEIRO, tp.CODIGO_LOJA, tp.CODIGO_PROMOTOR, tp.ORG_LOGO, tp.MIGRACAO, tp.DESCRITIVO, tp.QUANTIDADE, CONVERT(DATE,tp.DATA_ACAO,103),
			 CONVERT(DATE,GETDATE ()) AS DATA_IMPORTACAO_ARQUIVO, 'TXT' ARQUIVO_IMPORTACAO from #BASE_TXT  as tp 
				where  not  EXISTS (select * from VENDA_DIARIA_NOVOFRONT as tf 
									where	tf.DATA_ACAO		= CONVERT(DATE,tp.DATA_ACAO,103))
END;

--executa procedure
EXEC  INPORT_TXT