--ALIMENTANDO A TABELA

	CREATE PROCEDURE INPORT_LOJA_XLS AS
	BEGIN
	INSERT INTO LOJA 
		SELECT	*,
			CONVERT(DATE,GETDATE()) AS DATA_IMPORTACAO
	FROM OPENROWSET (
		'Microsoft.ACE.OLEDB.12.0', 
		'Excel 12.0;Database=\\gru3wvamexdb1\Queries BI\2 - Monitorias\18 - Bradescard\BASES\BASE_LOJA.XLS;HDR=YES', 
		'SELECT * FROM [LOJAS$]')
	END
		
--EXECUTANDO PROCEDURE
EXECUTE INPORT_LOJA_XLS

SELECT * FROM LOJA

