--ALIMENTANDO A TABELA

	CREATE PROCEDURE INPORT_PARCEIRO_XLS AS
	BEGIN
	INSERT INTO PARCEIRO 
		SELECT	*
	FROM OPENROWSET (
		'Microsoft.ACE.OLEDB.12.0', 
		'Excel 12.0;Database=\\gru3wvamexdb1\Queries BI\2 - Monitorias\18 - Bradescard\BASES\BASE_LOJA.XLS;HDR=YES', 
		'SELECT * FROM [PARCEIRO$]')
	END
		
--EXECUTANDO PROCEDURE
EXECUTE INPORT_PARCEIRO_XLS

SELECT * FROM PARCEIRO

